gravitee-io/gravitee-ui-particles

.circleci/config.yml
README.md
ui-particles-angular/projects/ui-particles-angular/package.json
ui-particles-angular/projects/ui-particles-angular/src/stories/theme-color/showcase-color.component.ts
ui-particles-angular/projects/ui-particles-angular/src/stories/theme-typography/showcase-typography.component.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6444
Previously the packages of this repo were released on GitHub registry, everything was working great EXCEPT the fact users need to be authenticated (with a GitHub account) to download the packages.
So we decided to move back to npmjs like the `ui-component` package.
- GitHub post about Github Package Registry without authentication: https://github.community/t/download-from-github-package-registry-without-authentication/14407

ci: switch to npm registry

---

.circleci/config.yml
ui-particles-angular/.prettierignore
ui-particles-angular/.storybook/tsconfig.json
ui-particles-angular/angular.json
ui-particles-angular/package.json
ui-particles-angular/projects/ui-particles-angular/src/setup-jest.ts
ui-particles-angular/projects/ui-particles-angular/tsconfig.lib.json
ui-particles-angular/projects/ui-policy-studio-angular/.eslintrc.js
ui-particles-angular/projects/ui-policy-studio-angular/LICENSE.txt
ui-particles-angular/projects/ui-policy-studio-angular/README.md
ui-particles-angular/projects/ui-policy-studio-angular/index.scss
ui-particles-angular/projects/ui-policy-studio-angular/jest.config.js
ui-particles-angular/projects/ui-policy-studio-angular/ng-package.json
ui-particles-angular/projects/ui-policy-studio-angular/package.json
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/ui-policy-studio-angular.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/ui-policy-studio-angular.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/ui-policy-studio-angular.module.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/ui-policy-studio-angular.service.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/ui-policy-studio-angular.service.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/ui-policy-studio-angular.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/public-api.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/setup-jest.ts
ui-particles-angular/projects/ui-policy-studio-angular/tsconfig.lib.json
ui-particles-angular/projects/ui-policy-studio-angular/tsconfig.lib.prod.json
ui-particles-angular/projects/ui-policy-studio-angular/tsconfig.spec.json
ui-particles-angular/release.config.js
ui-particles-angular/tsconfig.json

**Issue**
https://github.com/gravitee-io/issues/issues/6892
- Add empty new angular package for policy studio 
- Config necessary for CI and release this new package
I think we need to merge prerelease inside one comment message 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-djqainxtqe.chromatic.com)

🧑‍🚀  Add new package for policy studio

---

ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/theme/color/gio-palettes.stories.scss

**Issue**
na
corrects the non-presence of lighter in mat-content-palette
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-loneqzsbds.chromatic.com)

fix: manage mat-content-palette like a special palette

---

ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss

**Issue**
na
angular 13.x error with color not exist in palette
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-nmdzycxwhd.chromatic.com)

fix: angular 13.x error with color not exist in palette

---

ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts

`GioIconsModule` was not exported in `public-api`, therefore we couldn't import it in our app 🙈
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-tkeogqmtbi.chromatic.com)

fix: export GioIconsModule

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6893
Add `hideTab` and `tabId`
when `hideTab = true` only `tabId` can change policy studio screen 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-rwwjscemla.chromatic.com)

Ps add menu

---

ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-theme.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-tabs.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-tabs.stories.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6765
Remove unnecessary min-width inside mat tabs to have smaller tabs when the text is not large 
cockpit seems to have the same feedback. what do you think about doing it globally ?
https://github.com/gravitee-io/gravitee-cockpit/blob/82cefaa5d99ada4d5907ada13ba813e7add31511/gravitee-cockpit-ui/src/app/designer/designer-model-edit/design/components/inspectors/inspector.scss#L17
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hqfkxofeqs.chromatic.com)

feat(mat-tabs): override material to remove tabs label min-width

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-icons/gio-icons.module.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-method-badge/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-method-badge/gio-method-badge.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-method-badge/gio-method-badge.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-components.scss

**Issue**
https://github.com/gravitee-io/issues/issues/7104
- I updated the style of the Badges to match the one in Figma (see screenshots below)
- I updated the story to display Badge in a column
- I removed `gio-badge` from the examples to enforce users to use one specific version of the badge. To avoid breaking change `gio-badge` is still available.
- I created `gio-method-badge-xxxx` classes
**Screenshot**
Figma ref: https://www.figma.com/file/XvLO9G5fPRIrfyhLjPg6a2/Gravitee_Lib_elemZ?node-id=1008%3A3721
_Before_
_After_
_Method Badge_
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-iipbcbnvhz.chromatic.com)

Update Badges with the new design and create Method Badge

---

ui-particles-angular/projects/ui-particles-angular/assets/gio-icons.svg

**Issue**
NA
- I removed unused icons from the sprite
- I added `currentColor` property to each path and group inside SVG to allow the color customization
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hevltahxqr.chromatic.com)

Remove unused icons & add color customization

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.scss

**Issue**
NA
Update design of the save bar to match new mockup available on [Figma](https://www.figma.com/file/XvLO9G5fPRIrfyhLjPg6a2/Gravitee_Lib_elemZ?node-id=1221%3A2315).
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-klgnhltchv.chromatic.com)

Update design of the save bar to match new mockup

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts

Component `form-tags-input` (already present in [gravitee-api-management](https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-console-webui/src/shared/components/gio-form-tags-input)) is common to multiple Gravitee products.
This PR relocates it, without modifying the actual behaviour.
[API-Management Storybook](https://612657caa8e859003a8a6430-cacbubogdv.chromatic.com/?path=/story/shared-form-tags-input--without-form-field)
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-ospqcoobma.chromatic.com)

feat: add form-tags-input component

---

ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts

Add the new component `form-tags-input` to ui-particles public api
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-shlaqiafwy.chromatic.com)

fix: add form-tags-input to public api

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-h5.scss

According to the mock-ups ([here](https://www.figma.com/file/XvLO9G5fPRIrfyhLjPg6a2/Gravitee_Lib_elemZ?node-id=516%3A1844)), `<h5>` bottom margin should be 4px
Bonus in this PR: adds the `with` method to form-tags-input`s harness to allow filtering.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-zjzalxsnux.chromatic.com)

fix: adjust h5 default bottom margin

---

ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/index.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts

Here are some small changes made on cockpit mat-buttons we will certainly find everywhere in a near future.
In this pull request I override the default radius and brightness of the mat buttons
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-lalwftrwky.chromatic.com)

feat: override mat-button style

---

ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/theme/color/showcase-color.component.html
ui-particles-angular/projects/ui-particles-angular/src/scss/theme/color/showcase-color.component.scss

Update mat palette colors.
Here is the link of the colors reference https://www.figma.com/file/XvLO9G5fPRIrfyhLjPg6a2/Gravitee_Lib_elemZ?node-id=1493%3A1143
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-wsnlzqmgbe.chromatic.com)

feat: update mat palette colors

---

ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss

**Issue**
na
use default color and not the contrast color for content palette because there is no contrast for this color
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-miubqabgur.chromatic.com)

fix: use default color and not the contrast color for content palette

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts

Add a ConfirmDialog component that could be embedded in a model to ask for confirmation from the user.
Once the dialog is closed, we received a boolean that allows us to know if the user has confirmed or canceled.
**Screenshots**
**Additional informations**
The component comes from [APIM](https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-console-webui/src/shared/components/gio-confirm-dialog)
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-adnmhndehw.chromatic.com)

feat: add gio-confirm-dialog component

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.scss

**Issue**
N.A.
For better accessibility, there need to be more contrast between background and text color in banners.
**Screenshot**
BEFORE
AFTER 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hbqgfwbplh.chromatic.com)

fix(banner): change text color to darker for accessibility

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.stories.ts

**Issue**
https://github.com/gravitee-io/issues/issues/8141
Add disabled state for gio form header 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-gkefoldlip.chromatic.com)

feat: add disable state for gio-form-headers compo

---

ui-particles-angular/package.json
ui-particles-angular/projects/ui-particles-angular/package.json
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-add-button/gio-form-file-picker-add-button.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-add-button/gio-form-file-picker-add-button.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-add-button/gio-form-file-picker-add-button.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-empty/gio-form-file-picker-empty.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-empty/gio-form-file-picker-empty.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/index.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
yarn.lock

**Issue**
N.A.
Add file input component
Code was originally created by @ThibaudAV [here](https://github.com/gravitee-io/gravitee-api-management/pull/2520). But as this component is also needed in Cockpit, we move it here in the common lib to be able to use in all products.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hkmriwvpby.chromatic.com)

feat: add file picker component

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts

**Issue**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-beydhyymzl.chromatic.com)

feat: add confirm and validate dialog component

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-label/gio-form-file-picker-label.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-label/gio-form-file-picker-label.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-label/gio-form-file-picker-label.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.stories.ts

Add optional label for file picker input :
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-lewstifgkb.chromatic.com)

Add optional label for file picker input

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.ts

**Issue**
n/a
By adding css hidden visibility when save bar is close
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hwtzxjupbi.chromatic.com)

fix: allows to interact with elements under the sticky save-bar

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.stories.ts

**Issue**
Improve banner to have optional body
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-fulwewnzke.chromatic.com)

feat: improve banner to have optional body

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.spec.ts

**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-127
Small fix to have gio-headers-component work with disabled state switch 
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-lpvlmpwkwl.chromatic.com)

Small fix to have gio-headers-component work with disabled state switch 

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.stories.ts

**Issue**
n/a
Adds a default margin under each form field to have 2 error & hint lines. 
Removes the added margin between form fields as it is not compatible with a `flex-direction: row`
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-vdfpnuawab.chromatic.com)

Fix form field

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.service.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.module.ts

**Issue**
N.A.
Make GioMenuService singleton
When using in Cockpit in different modules that are lazy loaded, we had several instances of the GioMenuService, causing the submenu not to collapse when collapsing the main menu.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hijsokvuwm.chromatic.com)

fix: make menu service singleton

---

ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-576
Create a story to show buttons as they are defined in Figma 
https://www.figma.com/file/okDdv0Rs884yxKgXQROqaG/Perseverance-design-system?node-id=2067%3A23363&t=7hp2sZMBYASmzyR7-4
As you can see there is some difference between what we have in Particles vs the buttons defined in Figma 
The goal here is just to list buttons, and we have other issues to make them have a consistent look (subtasks of https://gravitee.atlassian.net/browse/APIM-575)
---

docs: add story to reflect button styles like defined in Figma

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-291
---
```
npm install @gravitee/ui-policy-studio-angular@5.1.0-291-keyboard-accessibility-5ff1643
```
```
yarn add @gravitee/ui-policy-studio-angular@5.1.0-291-keyboard-accessibility-5ff1643
```
---

fix(submenu): resolve submenu position when deal with escape key

---

ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.scss

**Issue**
N.A.
Improve mat-form-field layout
---
```
npm install @gravitee/ui-particles-angular@5.1.3-fix-mat-form-field-prefix-f0764ec
```
```
yarn add @gravitee/ui-particles-angular@5.1.3-fix-mat-form-field-prefix-f0764ec
```
---

fix(mat-form-field): apply styling on mat form field prefix

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/integer.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/null-type.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/wrappers/gio-banner-extension.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/wrappers/gio-form-field-wrapper.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/wrappers/gio-form-field-wrapper.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/wrappers/gio-form-field-wrapper.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-675
Add bannerTitle and bannerText on json form properties in order to add a banner with detailed information instead of having long hints
For instance, a field with this description
```
"bootstrapServers": {
"type": "string",
"title": "bootstrap.servers",
"description": "This list should be in the form host1:port1,host2:port2,...",
"widget": {
"formlyConfig": {
"props": {
"bannerTitle": "Bootstrap servers",
"bannerText": "A list of host/port pairs, separated by a comma, to use for establishing the initial connection to the Kafka cluster. The client will make use of all servers irrespective of which servers are specified here for bootstrapping—this list only impacts the initial hosts used to discover the full set of …
```

Add gio field wrapper

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss

**Issue**
https://github.com/gravitee-io/issues/issues/8867
https://gravitee.atlassian.net/browse/APIM-779
Display multiple spaces properly in Confirm and Validate dialog
---
```
npm install @gravitee/ui-policy-studio-angular@5.7.1-fix-multiple-spaces-display-260cf45
```
```
yarn add @gravitee/ui-policy-studio-angular@5.7.1-fix-multiple-spaces-display-260cf45
```
---

Display multiple spaces properly in Confirm and Validate dialog

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/multischema-type.component.ts

**Issue**
n/a
fix console error and support oneOf,.. with formly
But we need to complet this supported feature with dedicated exemple and test/validate more complex stuff
---
```
npm install @gravitee/ui-policy-studio-angular@5.7.1-multischema-150635a
```
```
yarn add @gravitee/ui-policy-studio-angular@5.7.1-multischema-150635a
```

fix: add mutltischema type component for GioFormJsonSchemaModule

---

ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-table.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-table.stories.ts

**Issue**
Not required but improve UI for
https://gravitee.atlassian.net/browse/APIM-653
And some others like path table inside api creation workflow
With this override : 
Without :
---
```
npm install @gravitee/ui-particles-angular@5.7.3-table-form-field-62c3e2d
```
```
yarn add @gravitee/ui-particles-angular@5.7.3-table-form-field-62c3e2d
```
---

feat: improve use of mat-form-field inside table

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.ts

**Issue**
n/a
Improve GioFormJsonSchemaComponent with ControlValueAccessor to simplify the use of JsonForm Input.
And connect dirty  & touched to be able to use it
---
```
npm install @gravitee/ui-policy-studio-angular@5.7.3-improve-form-json-compo-cb73491
```
```
yarn add @gravitee/ui-policy-studio-angular@5.7.3-improve-form-json-compo-cb73491
```
---

feat: impl ControlValueAccessor for GioFormJsonSchemaComponent

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid-ignore.directive.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.directive.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.harness.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts

**Issue**
Part of : https://gravitee.atlassian.net/browse/APIM-966
Allow to add inner content like button inside save-bar
Main goal is to add stepper next/back actions
---
```
npm install @gravitee/ui-particles-angular@5.19.1-feat-save-bar-5d4fc8b
```
```
yarn add @gravitee/ui-particles-angular@5.19.1-feat-save-bar-5d4fc8b
```
---
```
npm install @gravitee/ui-policy-studio-angular@5.19.1-feat-save-bar-5d4fc8b
```
```
yarn add @gravitee/ui-policy-studio-angular@5.19.1-feat-save-bar-5d4fc8b
```
---

feat: allow to add inner content like button inside save-bar

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-table-light/gio-table-light.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-theme-variable.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/index.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/theme/color/gio-palettes.stories.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/theme/color/showcase-color.component.scss

**Issue**
n/a
BREAKING CHANGE: removes deprecated colors. To migrate use the following correspondence:
$mat-neutral-palette (default) -> $mat-dove-palette (darker10)
$mat-neutral-palette (darker) -> $mat-dove-palette (darker70)
$mat-neutral-palette (lighter) -> $mat-dove-palette (default)
$mat-content-palette (default) -> $mat-space-palette (lighter40) 
$mat-content-palette (darker) -> $mat-space-palette (default), 
$mat-content-palette (disabled): $mat-basic-palette (disabled) 
$mat-content-palette (lighter) -> $mat-basic-palette (white)
$mat-decorative-palette (background) -> $mat-dove-palette (default) 
$mat-decorative-palette (lighter-background) -> $mat-dove-palette (default) 
$mat-decorative-palette (surface) -> $mat-basic-palette (white) 
$mat-decorative-palette …

refactor: remove deprecated colors

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.module.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/ApiType.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/testing/harnesses/div.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/testing/harnesses/index.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/testing/index.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1548
Add empty flows display for policy studio
---
```
npm install @gravitee/ui-particles-angular@7.0.0-apim-1548-init-layout-9ffda4a
```
```
yarn add @gravitee/ui-particles-angular@7.0.0-apim-1548-init-layout-9ffda4a
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.0.0-apim-1548-init-layout-31e6d58
```
```
yarn add @gravitee/ui-policy-studio-angular@7.0.0-apim-1548-init-layout-31e6d58
```
---

Policy studio - Init the layout with empty flows display

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.module.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1550
Add create / edit / delete  message flow
Next PR : same dialog but for proxy flow. Maybe i rename this dialog or not if a change only the content, we will see
---
```
npm install @gravitee/ui-policy-studio-angular@7.3.0-apim-1550-crud-message-flow-c4fb521
```
```
yarn add @gravitee/ui-policy-studio-angular@7.3.0-apim-1550-crud-message-flow-c4fb521
```
---
```
npm install @gravitee/ui-particles-angular@7.3.0-apim-1550-crud-message-flow-c4fb521
```
```
yarn add @gravitee/ui-particles-angular@7.3.0-apim-1550-crud-message-flow-c4fb521
```
---

Policy studio - Add create / edit / delete  message flow

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts

use http methods selection as example
**Issue**
n/a
---
```
npm install @gravitee/ui-policy-studio-angular@7.5.0-tag-http-methos-b2b5c0d
```
```
yarn add @gravitee/ui-policy-studio-angular@7.5.0-tag-http-methos-b2b5c0d
```
---
```
npm install @gravitee/ui-particles-angular@7.5.0-tag-http-methos-b2b5c0d
```
```
yarn add @gravitee/ui-particles-angular@7.5.0-tag-http-methos-b2b5c0d
```
---

chore: add story - tags input with autocomplete selection only

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-message-form-dialog/gio-ps-flow-message-form-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-message-form-dialog/gio-ps-flow-message-form-dialog.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/HttpMethod.ts

**Issue**
N.A.
- Add suffix to path input in flow sync edit dialog
- Add init test for proxy and message dialogs
---
```
npm install @gravitee/ui-policy-studio-angular@7.7.1-add-flow-edit-test-4674153
```
```
yarn add @gravitee/ui-policy-studio-angular@7.7.1-add-flow-edit-test-4674153
```
---
```
npm install @gravitee/ui-particles-angular@7.7.1-add-flow-edit-test-4674153
```
```
yarn add @gravitee/ui-particles-angular@7.7.1-add-flow-edit-test-4674153
```
---

Add flow edit test

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog-result.model.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.module.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/SaveOutput.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/FlowExecution.fixture.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1552
This PR adds a new form dialog to edit the flox execution configuration of an API and uses it in the new policy studio
---
```
npm install @gravitee/ui-policy-studio-angular@7.7.1-apim-1552-select-flow-mode-bdede0e
```
```
yarn add @gravitee/ui-policy-studio-angular@7.7.1-apim-1552-select-flow-mode-bdede0e
```
---
```
npm install @gravitee/ui-particles-angular@7.7.1-apim-1552-select-flow-mode-bdede0e
```
```
yarn add @gravitee/ui-particles-angular@7.7.1-apim-1552-select-flow-mode-bdede0e
```
---

Configure the flow execution in the Policy Studio

---

ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-method-badge/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-method-badge/gio-method-badge.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-method-badge/gio-method-badge.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1921
The HTTP verb is OPTIONS so the badge mechanism tries to apply the CSS style `gio-method-badge-options` but can't find it.
See https://github.com/gravitee-io/gravitee-ui-particles/blob/main/ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts#L115
---
```
npm install @gravitee/ui-particles-angular@7.10.0-apim-1921-fix-option-badge-4cf8db1
```
```
yarn add @gravitee/ui-particles-angular@7.10.0-apim-1921-fix-option-badge-4cf8db1
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.10.0-apim-1921-fix-option-badge-4cf8db1
```
```
yarn add @gravitee/ui-policy-studio-angular@7.10.0-apim-1921-fix-option-badge-4cf8db1
```
---

fix: the HTTP verb OPTIONS ends with an S

---

ui-particles-angular/.storybook/tsconfig.json
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-message-form-dialog/gio-ps-flow-message-form-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.module.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/Step.fixture.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1554
- Improve chromatic usage
- fix storybook configuration
- add policy configuration form when editing/ adding policy into flow phase
---
```
npm install @gravitee/ui-policy-studio-angular@7.14.0-policy-studio-step-8-b0320ce
```
```
yarn add @gravitee/ui-policy-studio-angular@7.14.0-policy-studio-step-8-b0320ce
```
---
```
npm install @gravitee/ui-particles-angular@7.14.0-policy-studio-step-8-b0320ce
```
```
yarn add @gravitee/ui-particles-angular@7.14.0-policy-studio-step-8-b0320ce
```
---

Policy studio step 8

---

ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-table-light/gio-table-light.scss

**Issue**
https://gravitee.atlassian.net/browse/APIM-1415
Update `.gio-table-light` style to avoid to copy paste it everywhere
---
```
npm install @gravitee/ui-policy-studio-angular@7.15.0-apim-1415-table-style-c615123
```
```
yarn add @gravitee/ui-policy-studio-angular@7.15.0-apim-1415-table-style-c615123
```
---
```
npm install @gravitee/ui-particles-angular@7.15.0-apim-1415-table-style-c615123
```
```
yarn add @gravitee/ui-particles-angular@7.15.0-apim-1415-table-style-c615123
```
---

feat: update gio-table-light style

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts

**Issue**
n/a
Try to fix and stabilise this component .. btw apim console & test & policy studio 
---
```
npm install @gravitee/ui-particles-angular@7.16.1-fix-ps-6a2ed04
```
```
yarn add @gravitee/ui-particles-angular@7.16.1-fix-ps-6a2ed04
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.16.1-fix-ps-6a2ed04
```
```
yarn add @gravitee/ui-policy-studio-angular@7.16.1-fix-ps-6a2ed04
```
---

fix(json-schema): move stateChanges subscribe into ngAfterViewInit

---

ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1938
---
```
npm install @gravitee/ui-particles-angular@7.21.1-improve-btn-e5ff837
```
```
yarn add @gravitee/ui-particles-angular@7.21.1-improve-btn-e5ff837
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.21.1-improve-btn-e5ff837
```
```
yarn add @gravitee/ui-policy-studio-angular@7.21.1-improve-btn-e5ff837
```
---

feat: add mat-icon-right class for right icon in btn

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-1416
When a user enable / disable the form fields, using a toggle for example, we don't want to have observable errors in the logs ( see https://github.com/gravitee-io/gravitee-ui-particles/pull/267#pullrequestreview-1500114670 )
Here is a fix to ensure it not happens and that the added fields are consistent with the global state of the form.
https://github.com/gravitee-io/gravitee-ui-particles/assets/25704259/4f27f7a2-8c79-42bb-99f5-66f9530a6537
---
```
npm install @gravitee/ui-policy-studio-angular@7.22.1-apim-1416-enable-disable-form-70f7ec2
```
```
yarn add @gravitee/ui-policy-studio-angular@7.22.1-apim-1416-enable-disable-form-70f7ec2
```
---
```
npm install …
```

fix: check disabled state of array fields after adding an item

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.base.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-2088
Improve json-schema GioUiTypeConfig to allow to pass props
---
```
npm install @gravitee/ui-particles-angular@7.24.2-json-schema-fd74fb5
```
```
yarn add @gravitee/ui-particles-angular@7.24.2-json-schema-fd74fb5
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.24.2-json-schema-fd74fb5
```
```
yarn add @gravitee/ui-policy-studio-angular@7.24.2-json-schema-fd74fb5
```
---

feat: improve json-schema GioUiTypeConfig to allow to pass props

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/headers-type.component.ts

fix APIM-2134
before this gio-form-headers convert the key attribute of header object to name attribute but when the data using "name" attribute is injected, the key field wasn't updated propertly.
This fix apply a bidirectionnal mapping.
---
```
npm install @gravitee/ui-particles-angular@7.24.2-apim-2134-6142ef5
```
```
yarn add @gravitee/ui-particles-angular@7.24.2-apim-2134-6142ef5
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.24.2-apim-2134-6142ef5
```
```
yarn add @gravitee/ui-policy-studio-angular@7.24.2-apim-2134-6142ef5
```
---

fix: improve mapping of header values in gio-form-headers

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/Step.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/policy/Policy.fixture.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/policy/Policy.ts

see https://gravitee.atlassian.net/browse/APIM-1935
---
```
npm install @gravitee/ui-policy-studio-angular@7.26.0-lock-policy-studio-v4-36bd70a
```
```
yarn add @gravitee/ui-policy-studio-angular@7.26.0-lock-policy-studio-v4-36bd70a
```
---
```
npm install @gravitee/ui-particles-angular@7.26.0-lock-policy-studio-v4-36bd70a
```
```
yarn add @gravitee/ui-particles-angular@7.26.0-lock-policy-studio-v4-36bd70a
```
---

feat: display cta banner when an un-deployed policy is selected

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/enum.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts

**Issue**
n/a
Add `enumLabelMap` to set label to json-schema enum
Improve GioFormTagsInputComponent to add dynamic search autocomplete
---

Improvement for  GioFormJsonSchema & GioFormTagsInputComponent

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/policy/Policy.fixture.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-2132
Sort policies categories and push "others" at the end
---
```
npm install @gravitee/ui-particles-angular@7.28.0-apim-2132-sort-policy-filters-86c4ee5
```
```
yarn add @gravitee/ui-particles-angular@7.28.0-apim-2132-sort-policy-filters-86c4ee5
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.28.0-apim-2132-sort-policy-filters-86c4ee5
```
```
yarn add @gravitee/ui-policy-studio-angular@7.28.0-apim-2132-sort-policy-filters-86c4ee5
```
---

fix: sort policies categories

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.stories.ts

see https://gravitee.atlassian.net/browse/APIM-2157
---
```
npm install @gravitee/ui-particles-angular@7.26.0-fix-light-submenu-title-15b961a
```
```
yarn add @gravitee/ui-particles-angular@7.26.0-fix-light-submenu-title-15b961a
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.26.0-fix-light-submenu-title-15b961a
```
```
yarn add @gravitee/ui-policy-studio-angular@7.26.0-fix-light-submenu-title-15b961a
```
---

fix: add light theme option to submenu group

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html

see https://gravitee.atlassian.net/browse/APIM-1685
---
```
npm install @gravitee/ui-particles-angular@7.28.2-trial-url-proxy-87d390d
```
```
yarn add @gravitee/ui-particles-angular@7.28.2-trial-url-proxy-87d390d
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.28.2-trial-url-proxy-87d390d
```
```
yarn add @gravitee/ui-policy-studio-angular@7.28.2-trial-url-proxy-87d390d
```
---

fix: add trial url to proxy policies

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts

**Issue**
https://github.com/gravitee-io/issues/issues/2023
Add a boolean to accept only tags available in autocomplete options
---
```
npm install @gravitee/ui-policy-studio-angular@7.28.2-use-autocomplete-options-only-d8afa02
```
```
yarn add @gravitee/ui-policy-studio-angular@7.28.2-use-autocomplete-options-only-d8afa02
```
---
```
npm install @gravitee/ui-particles-angular@7.28.2-use-autocomplete-options-only-d8afa02
```
```
yarn add @gravitee/ui-particles-angular@7.28.2-use-autocomplete-options-only-d8afa02
```
---

Add a boolean to accept only tags available in autocomplete options

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts

**Issue**
When the menu is collapse and go to organization level, the menu is not display.
---
```
npm install @gravitee/ui-policy-studio-angular@7.28.5-fix-org-submenu-a4d87dc
```
```
yarn add @gravitee/ui-policy-studio-angular@7.28.5-fix-org-submenu-a4d87dc
```
---
```
npm install @gravitee/ui-particles-angular@7.28.5-fix-org-submenu-a4d87dc
```
```
yarn add @gravitee/ui-particles-angular@7.28.5-fix-org-submenu-a4d87dc
```
---

fix(gio-submenu): add static input flag to force submenu renderer

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/multischema-type.component.ts

**Issue**
Disable mat-select in json-schema-form component
---
```
npm install @gravitee/ui-particles-angular@7.28.6-fix-disable-multiform-select-6a8a04e
```
```
yarn add @gravitee/ui-particles-angular@7.28.6-fix-disable-multiform-select-6a8a04e
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.28.6-fix-disable-multiform-select-6a8a04e
```
```
yarn add @gravitee/ui-policy-studio-angular@7.28.6-fix-disable-multiform-select-6a8a04e
```
---

fix: disable mutlischema mat-select when form is disabled

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.ts

---
```
npm install @gravitee/ui-policy-studio-angular@7.29.1-fix-license-directive-0218d90
```
```
yarn add @gravitee/ui-policy-studio-angular@7.29.1-fix-license-directive-0218d90
```
---
```
npm install @gravitee/ui-particles-angular@7.29.1-fix-license-directive-0218d90
```
```
yarn add @gravitee/ui-particles-angular@7.29.1-fix-license-directive-0218d90
```
---

fix(license): remove storybook stuff from implementation

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts

**Issue**
n/a
Not emit valueChanges by default on init.
Like native input element emit valueChanges only after changes
---
```
npm install @gravitee/ui-particles-angular@7.29.2-fix-json-schema-c8b0d57
```
```
yarn add @gravitee/ui-particles-angular@7.29.2-fix-json-schema-c8b0d57
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.29.2-fix-json-schema-c8b0d57
```
```
yarn add @gravitee/ui-policy-studio-angular@7.29.2-fix-json-schema-c8b0d57
```
---

fix(json-schema): not emit valueChanges by default on init

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts

**Issue**
Necessary for https://gravitee.atlassian.net/browse/APIM-2792
Enable markdown language config for gio-monaco-editor
---
```
npm install @gravitee/ui-policy-studio-angular@7.37.2-allow-md-in-monaco-editor-2205d0b
```
```
yarn add @gravitee/ui-policy-studio-angular@7.37.2-allow-md-in-monaco-editor-2205d0b
```
---
```
npm install @gravitee/ui-particles-angular@7.37.2-allow-md-in-monaco-editor-2205d0b
```
```
yarn add @gravitee/ui-particles-angular@7.37.2-allow-md-in-monaco-editor-2205d0b
```
---

fix: enable markdown in monaco editor

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-loader/gio-loader.component.scss

The autocomplete options will only be called when the component has the
focus. It prevents calling the async options for nothing, like when
the user doesn't interact with the component.
I didn't manage to prevent calling autocomplete options after selecting
a value. In that case, the input loses the focus and re-gains it just after, triggering the call of autocomplete options
---
```
npm install @gravitee/ui-policy-studio-angular@7.37.5-fix-gio-form-tags-input-fetch-on-focus-c34410c
```
```
yarn add @gravitee/ui-policy-studio-angular@7.37.5-fix-gio-form-tags-input-fetch-on-focus-c34410c
```
---
```
npm install @gravitee/ui-particles-angular@7.37.5-fix-gio-form-tags-input-fetch-on-focus-c34410c
```
```
yarn add …
```

fix(gio-form-tags-input): call autocomplete options on focus

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-icon.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-wrapper.component.ts

**Issue**
https://gravitee.atlassian.net/browse/COC-478
---
```
npm install @gravitee/ui-particles-angular@7.38.0-coc-478-sso-design-f9edfb4
```
```
yarn add @gravitee/ui-particles-angular@7.38.0-coc-478-sso-design-f9edfb4
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.38.0-coc-478-sso-design-f9edfb4
```
```
yarn add @gravitee/ui-policy-studio-angular@7.38.0-coc-478-sso-design-f9edfb4
```
---

fix: use type=btn on clipboard to prevent form submit

---

ui-particles-angular/.stylelintrc.js
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-footer/gio-menu-footer.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-item/gio-submenu-item.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-oem-palette.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/index.scss

**Issue**
https://gravitee.atlassian.net/browse/APIM-3109
Customize menu colors.
---
```
npm install @gravitee/ui-particles-angular@7.38.0-menu-customization-976b00f
```
```
yarn add @gravitee/ui-particles-angular@7.38.0-menu-customization-976b00f
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.38.0-menu-customization-976b00f
```
```
yarn add @gravitee/ui-policy-studio-angular@7.38.0-menu-customization-976b00f
```
---

Customize menu colors

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-badge/gio-badge.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-footer/gio-menu-footer.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-item/gio-menu-item.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-selector/gio-menu-selector.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu-group/gio-submenu-group.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu-item/gio-submenu-item.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-top-bar/gio-top-bar-content/gio-top-bar-content.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-top-bar/gio-top-bar-link/gio-top-bar-link.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-top-bar/gio-top-bar-menu/gio-top-bar-menu.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-top-bar/gio-top-bar.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-top-bar/gio-top-bar.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme-menu-and-top-bar.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme-shared.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-oem-palette-variable.scss

**Issue**
https://github.com/gravitee-io/issues/issues/3111
- Refactoring to centralize shared content / standardize variables
- Add oem customization to top bar 
Default: 
Dark mode:
Light mode:
---
```
npm install @gravitee/ui-policy-studio-angular@7.42.0-apim-3111-adapt-gio-top-bar-4c8bd1b
```
```
yarn add @gravitee/ui-policy-studio-angular@7.42.0-apim-3111-adapt-gio-top-bar-4c8bd1b
```
---
```
npm install @gravitee/ui-particles-angular@7.42.0-apim-3111-adapt-gio-top-bar-4c8bd1b
```
```
yarn add @gravitee/ui-particles-angular@7.42.0-apim-3111-adapt-gio-top-bar-4c8bd1b
```
---

Apim 3111 adapt gio top bar

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme-menu-and-top-bar.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme-shared.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-2952
Remove dark mode option for now for OEM menu.
Add documentation for color customization of OEM menu.
---
```
npm install @gravitee/ui-particles-angular@7.43.0-apim-2952-add-doc-and-remove-dark-mode-6ef480b
```
```
yarn add @gravitee/ui-particles-angular@7.43.0-apim-2952-add-doc-and-remove-dark-mode-6ef480b
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.43.0-apim-2952-add-doc-and-remove-dark-mode-6ef480b
```
```
yarn add @gravitee/ui-policy-studio-angular@7.43.0-apim-2952-add-doc-and-remove-dark-mode-6ef480b
```
---

Apim 2952 add doc and remove dark mode

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-oem-palette-variable.scss
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-oem-palette.scss

**Issue**
https://gravitee.atlassian.net/browse/APIM-3236
Customize light sub-menu for oem 
Default: 
Customized:
---
```
npm install @gravitee/ui-policy-studio-angular@7.44.0-apim-3236-customize-light-sub-menu-05df2e9
```
```
yarn add @gravitee/ui-policy-studio-angular@7.44.0-apim-3236-customize-light-sub-menu-05df2e9
```
---

feat(oem): customize light submenu

---

ui-particles-angular/.storybook/preview.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-asciidoctor/gio-asciidoctor.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-icons/gio-icons.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-icons/gio-icons.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.spec.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts

**Issue**
n/a 
/!\ This module `HttpClientModule` must only be loaded once by the main application.
---
```
npm install @gravitee/ui-particles-angular@7.45.0-fix-httpclientmodule-055dc04
```
```
yarn add @gravitee/ui-particles-angular@7.45.0-fix-httpclientmodule-055dc04
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.45.0-fix-httpclientmodule-055dc04
```
```
yarn add @gravitee/ui-policy-studio-angular@7.45.0-fix-httpclientmodule-055dc04
```
---

fix: remove unnecessary HttpClientModule

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

**Issue**
N.A.
Add new service to check if license has the OEM feature
---
```
npm install @gravitee/ui-policy-studio-angular@7.47.0-add-method-to-license-service-068d4d6
```
```
yarn add @gravitee/ui-policy-studio-angular@7.47.0-add-method-to-license-service-068d4d6
```
---
```
npm install @gravitee/ui-particles-angular@7.47.0-add-method-to-license-service-068d4d6
```
```
yarn add @gravitee/ui-particles-angular@7.47.0-add-method-to-license-service-068d4d6
```
---

feat: add isOEM method in license service

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.testing.module.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-2966
UTM parameters should be appended to CTA URL only for non OEM usage
---
```
npm install @gravitee/ui-policy-studio-angular@7.48.0-optional-utm-params-in-cta-url-23f2c73
```
```
yarn add @gravitee/ui-policy-studio-angular@7.48.0-optional-utm-params-in-cta-url-23f2c73
```
---
```
npm install @gravitee/ui-particles-angular@7.48.0-optional-utm-params-in-cta-url-23f2c73
```
```
yarn add @gravitee/ui-particles-angular@7.48.0-optional-utm-params-in-cta-url-23f2c73
```
---

feat: make utm parameters optional in CTA URLs

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-selector/gio-menu-selector.component.scss

**Issue**
https://gravitee.atlassian.net/browse/APIM-3270
Fix arrow color in gio-menu-selector
---
```
npm install @gravitee/ui-particles-angular@7.49.0-fix-arrow-color-in-gio-menu-selector-c621ed5
```
```
yarn add @gravitee/ui-particles-angular@7.49.0-fix-arrow-color-in-gio-menu-selector-c621ed5
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.49.0-fix-arrow-color-in-gio-menu-selector-c621ed5
```
```
yarn add @gravitee/ui-policy-studio-angular@7.49.0-fix-arrow-color-in-gio-menu-selector-c621ed5
```
---

fix(gio-menu): apply color to arrow in Organization select

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-selector/gio-menu-selector.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-selector/gio-menu-selector.component.ts

**Issue**
N.A.
Remove disabled state on env select when only one env exists
---
```
npm install @gravitee/ui-policy-studio-angular@7.49.1-remove-disable-state-on-env-selection-21002c1
```
```
yarn add @gravitee/ui-policy-studio-angular@7.49.1-remove-disable-state-on-env-selection-21002c1
```
---
```
npm install @gravitee/ui-particles-angular@7.49.1-remove-disable-state-on-env-selection-21002c1
```
```
yarn add @gravitee/ui-particles-angular@7.49.1-remove-disable-state-on-env-selection-21002c1
```
---

fix(gio-menu): remove disable state on selector when only one value

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/README.stories.mdx
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-3395
Add option to disable minimap view on the monaco editor
---
```
npm install @gravitee/ui-policy-studio-angular@7.49.2-apim-3395-disable-minimap-3cc8744
```
```
yarn add @gravitee/ui-policy-studio-angular@7.49.2-apim-3395-disable-minimap-3cc8744
```
---

feat(monaco-editor): add option to disable minimap

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.harness.ts

**Issue**
n/a
Needed for apim wih angular-cli and angular 14 
Fix this error : 
```
...node_modules/@gravitee/ui-policy-studio-angular/fesm2020/gravitee-ui-policy-studio-angular-testing.mjs:820:16: ERROR: Transforming for-await loops to the configured target environment ("es2015") is not supported yet
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.51.0-fix-2542a1e
```
```
yarn add @gravitee/ui-policy-studio-angular@7.51.0-fix-2542a1e
```
---
```
npm install @gravitee/ui-particles-angular@7.51.0-fix-ebe667c
```
```
yarn add @gravitee/ui-particles-angular@7.51.0-fix-ebe667c
```
---

refactor: remove `for await` use parallel instead

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-info-bar/gio-ps-flow-details-info-bar.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-info-bar/gio-ps-flow-details-info-bar.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.scss
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-3026
Do not transform text for flow condition badges
---
```
npm install @gravitee/ui-policy-studio-angular@7.51.1-apim-3026-keep-text-formatting-for-flow-conditions-95c46c7
```
```
yarn add @gravitee/ui-policy-studio-angular@7.51.1-apim-3026-keep-text-formatting-for-flow-conditions-95c46c7
```
---
```
npm install @gravitee/ui-particles-angular@7.51.1-apim-3026-keep-text-formatting-for-flow-conditions-95c46c7
```
```
yarn add @gravitee/ui-particles-angular@7.51.1-apim-3026-keep-text-formatting-for-flow-conditions-95c46c7
```
---

feat(policy-studio): keep original text formatting for flow conditions

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-3562
Add a method in license service to be able to check a list of features is included in the license.
---
```
npm install @gravitee/ui-particles-angular@7.52.0-apim-3562-check-multiple-license-features-4c8990a
```
```
yarn add @gravitee/ui-particles-angular@7.52.0-apim-3562-check-multiple-license-features-4c8990a
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.52.0-apim-3562-check-multiple-license-features-4c8990a
```
```
yarn add @gravitee/ui-policy-studio-angular@7.52.0-apim-3562-check-multiple-license-features-4c8990a
```
---

Check multiple license features

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-3664
Add expiration date to license for UI
---
```
npm install @gravitee/ui-particles-angular@7.55.0-apim-3664-add-exp-date-to-license-fc57e0c
```
```
yarn add @gravitee/ui-particles-angular@7.55.0-apim-3664-add-exp-date-to-license-fc57e0c
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.55.0-apim-3664-add-exp-date-to-license-fc57e0c
```
```
yarn add @gravitee/ui-policy-studio-angular@7.55.0-apim-3664-add-exp-date-to-license-fc57e0c
```
---

feat: add expiration date to license + service

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

**Issue**
Change method name to match `expiresAt`. 
---
```
npm install @gravitee/ui-particles-angular@7.56.1-apim-3670-update-license-service-expires-at-afbfef9
```
```
yarn add @gravitee/ui-particles-angular@7.56.1-apim-3670-update-license-service-expires-at-afbfef9
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.56.1-apim-3670-update-license-service-expires-at-092fe5f
```
```
yarn add @gravitee/ui-policy-studio-angular@7.56.1-apim-3670-update-license-service-expires-at-092fe5f
```
---

feat: change method name to match `expiresAt` returned by /license

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.ts

When the form control controlling this input is updated, the component doesn't refresh. This PR fix that.
---
```
npm install @gravitee/ui-policy-studio-angular@7.57.0-fix-gio-form-tags-input-refresh-by-form-control-50d8a25
```
```
yarn add @gravitee/ui-policy-studio-angular@7.57.0-fix-gio-form-tags-input-refresh-by-form-control-50d8a25
```
---
```
npm install @gravitee/ui-particles-angular@7.57.0-fix-gio-form-tags-input-refresh-by-form-control-50d8a25
```
```
yarn add @gravitee/ui-particles-angular@7.57.0-fix-gio-form-tags-input-refresh-by-form-control-50d8a25
```
---

fix(gio-form-tags-input): refresh on form control changes

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-selector/gio-menu-selector.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-top-bar/gio-top-bar.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme-menu-and-top-bar.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme.service.ts
ui-particles-angular/projects/ui-particles-angular/src/scss/gio-oem-palette-variable.scss

**Issues**
https://gravitee.atlassian.net/browse/APIM-3784
https://gravitee.atlassian.net/browse/APIM-3783
- Drop-down menu for gio-menu-selector using primary colors for the default version and personalized with `menuActive` for oem customers
- Touching up gio license expiration notification styling after angular migration

fix: gio menu selector drop-down + license notif formatting

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-3856
Add scope to the license object so that it can be used in APIM
Added from backend with: https://github.com/gravitee-io/gravitee-api-management/pull/6560
---
```
npm install @gravitee/ui-policy-studio-angular@9.0.3-apim-2856-add-scope-to-license-4110426
```
```
yarn add @gravitee/ui-policy-studio-angular@9.0.3-apim-2856-add-scope-to-license-4110426
```
---
```
npm install @gravitee/ui-particles-angular@9.0.3-apim-2856-add-scope-to-license-4110426
```
```
yarn add @gravitee/ui-particles-angular@9.0.3-apim-2856-add-scope-to-license-4110426
```
---

feat(ui-angular): add scope to License object

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts

**Issue**
n/a
---
```
npm install @gravitee/ui-particles-angular@9.0.3-html-monacoeditor-afa8d1e
```
```
yarn add @gravitee/ui-particles-angular@9.0.3-html-monacoeditor-afa8d1e
```
---

Add support for html language into MonacoEditor

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.component.scss

**Issue**
This reverts commit 6737b84300eb854cbc987b25fd451863aaa3fb38.
---
```
npm install @gravitee/ui-particles-angular@9.5.0-revert-search-border-size-ad3fb1f
```
```
yarn add @gravitee/ui-particles-angular@9.5.0-revert-search-border-size-ad3fb1f
```
---
```
npm install @gravitee/ui-policy-studio-angular@9.5.0-revert-search-border-size-ad3fb1f
```
```
yarn add @gravitee/ui-policy-studio-angular@9.5.0-revert-search-border-size-ad3fb1f
```
---

fix: increase search border size

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-selector/gio-menu-selector.component.scss

use same border for env selector and search in menu
---
```
npm install @gravitee/ui-particles-angular@9.5.1-apim-3442-fix-background-color-4dc8af2
```
```
yarn add @gravitee/ui-particles-angular@9.5.1-apim-3442-fix-background-color-4dc8af2
```
---
```
npm install @gravitee/ui-policy-studio-angular@9.5.1-apim-3442-fix-background-color-4dc8af2
```
```
yarn add @gravitee/ui-policy-studio-angular@9.5.1-apim-3442-fix-background-color-4dc8af2
```
---

fix: use same border for env selector and search in menu

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.stories.component.ts

**Issue**
n/a
Simple BC for this component :
- Replace 'contentComponentInputs' with direct @Input property
Only one change near to this component https://github.com/gravitee-io/gravitee-cockpit/blob/394f796e429abc9103837c012b188f9650b480af/gravitee-cockpit-ui/src/app/topology/pages/account-settings/account-tokens/account-tokens.component.ts#L98
---
```
npm install @gravitee/ui-policy-studio-angular@9.6.0-confirm-dialog-e0200c9
```
```
yarn add @gravitee/ui-policy-studio-angular@9.6.0-confirm-dialog-e0200c9
```
---
```
npm install @gravitee/ui-particles-angular@9.6.0-confirm-dialog-e0200c9
```
```
yarn add @gravitee/ui-particles-angular@9.6.0-confirm-dialog-e0200c9
```
---

feat: improve confirm dialog with last angular 16 feature

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

BREAKING CHANGE: The GioLicenseService+isMissingFeature$ signature is modified to accept the feature as a string parameter instead of LicenseOptions object.
**Issue**
---
```
npm install @gravitee/ui-particles-angular@10.2.0-change-license-service-08f7b10
```
```
yarn add @gravitee/ui-particles-angular@10.2.0-change-license-service-08f7b10
```
---
```
npm install @gravitee/ui-policy-studio-angular@10.2.0-change-license-service-08f7b10
```
```
yarn add @gravitee/ui-policy-studio-angular@10.2.0-change-license-service-08f7b10
```
---

feat: change signature of isMissingFeature$ in license service

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.ts

**Issue**
n/a
allow license directive input with undefined license
---
```
npm install @gravitee/ui-policy-studio-angular@11.0.0-fix-license-b4189bf
```
```
yarn add @gravitee/ui-policy-studio-angular@11.0.0-fix-license-b4189bf
```
---
```
npm install @gravitee/ui-particles-angular@11.0.0-fix-license-b4189bf
```
```
yarn add @gravitee/ui-particles-angular@11.0.0-fix-license-b4189bf
```
---

fix: allow license directive input with undefined license

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-4216
Round the countdown number for the license expiration countdown.
---
```
npm install @gravitee/ui-policy-studio-angular@12.0.0-apim-4216-fix-decimal-license-countdown-ce4e059
```
```
yarn add @gravitee/ui-policy-studio-angular@12.0.0-apim-4216-fix-decimal-license-countdown-ce4e059
```
---
```
npm install @gravitee/ui-particles-angular@12.0.0-apim-4216-fix-decimal-license-countdown-ce4e059
```
```
yarn add @gravitee/ui-particles-angular@12.0.0-apim-4216-fix-decimal-license-countdown-ce4e059
```

fix(angular): round license expiration countdown number

---

.circleci/config.yml

Remove only-changed turbosnap option
---
```
npm install @gravitee/ui-policy-studio-angular@12.0.0-disable-chromatic-turbosnap-636dfd5
```
```
yarn add @gravitee/ui-policy-studio-angular@12.0.0-disable-chromatic-turbosnap-636dfd5
```
---
```
npm install @gravitee/ui-particles-angular@12.0.0-disable-chromatic-turbosnap-636dfd5
```
```
yarn add @gravitee/ui-particles-angular@12.0.0-disable-chromatic-turbosnap-636dfd5
```
---

chore: disable turbosnap on chromatic

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/kafka-advanced.ts

**Issue**
part of https://gravitee.atlassian.net/browse/APIM-3969
When formly is initialised, it emits several values as it builds up little by little. The control value must therefore be kept synchronised. Sync is stopped when the component is ready.
cherry pick of : https://github.com/gravitee-io/gravitee-ui-particles/pull/381
---
```
npm install @gravitee/ui-particles-angular@7.57.0-7-x-fix-json-schema-a925b63
```
```
yarn add @gravitee/ui-particles-angular@7.57.0-7-x-fix-json-schema-a925b63
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.57.0-7-x-fix-json-schema-a925b63
```
```
yarn add @gravitee/ui-policy-studio-angular@7.57.0-7-x-fix-json-schema-a925b63
```
---

fix: json-schema - Set initial control value when fomly has more stable

---

.circleci/config.yml
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.spec.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-4216
Apply fix to support branch 11.x so that AM can use it. 
AM uses Angular 16 for the 4.3.0 release.
---
```
npm install @gravitee/ui-particles-angular@11.3.0-apim-4216-fix-license-expiration-countdown-1b26cdc
```
```
yarn add @gravitee/ui-particles-angular@11.3.0-apim-4216-fix-license-expiration-countdown-1b26cdc
```
---
```
npm install @gravitee/ui-policy-studio-angular@11.3.0-apim-4216-fix-license-expiration-countdown-1b26cdc
```
```
yarn add @gravitee/ui-policy-studio-angular@11.3.0-apim-4216-fix-license-expiration-countdown-1b26cdc
```
---

Apim 4216 fix license expiration countdown

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/data/el-schema.json
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/models/JSONSchemaAutoComplete.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-language-el.service.ts

see: https://gravitee.atlassian.net/browse/APIM-558
---
```
npm install @gravitee/ui-particles-angular@12.0.2-feat-monaco-spel-abac7fa
```
```
yarn add @gravitee/ui-particles-angular@12.0.2-feat-monaco-spel-abac7fa
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.0.2-feat-monaco-spel-abac7fa
```
```
yarn add @gravitee/ui-policy-studio-angular@12.0.2-feat-monaco-spel-abac7fa
```
---

feat: add spel language support to monaco editor

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts

see https://gravitee.atlassian.net/browse/GKO-21
---
```
npm install @gravitee/ui-particles-angular@12.3.0-feat-read-only-policy-studio-fe5e3b5
```
```
yarn add @gravitee/ui-particles-angular@12.3.0-feat-read-only-policy-studio-fe5e3b5
```
---
```
npm install @gravitee/ui-schematics@12.3.0-feat-read-only-policy-studio-fe5e3b5
```
```
yarn add @gravitee/ui-schematics@12.3.0-feat-read-only-policy-studio-fe5e3b5
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.3.0-feat-read-only-policy-studio-fe5e3b5
```
```
yarn add @gravitee/ui-policy-studio-angular@12.3.0-feat-read-only-policy-studio-fe5e3b5
```
---

feat: add read only option to policy studio

---

ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.harness.ts
ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts

This property can be access from the component and the method was flawed.
---
```
npm install @gravitee/ui-schematics@12.4.0-fix-studio-harness-a2e6885
```
```
yarn add @gravitee/ui-schematics@12.4.0-fix-studio-harness-a2e6885
```
---
```
npm install @gravitee/ui-particles-angular@12.4.0-fix-studio-harness-a2e6885
```
```
yarn add @gravitee/ui-particles-angular@12.4.0-fix-studio-harness-a2e6885
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.4.0-fix-studio-harness-a2e6885
```
```
yarn add @gravitee/ui-policy-studio-angular@12.4.0-fix-studio-harness-a2e6885
```
---

fix: isReadOnly method from policy studio harness

---

projects/ui-particles-angular/src/lib/gio-card-empty-state/gio-card-empty-state.component.html
projects/ui-particles-angular/testing/harnesses/div.harness.ts
projects/ui-particles-angular/testing/harnesses/span.harness.ts
projects/ui-schematics/schematics/collection.json
projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__-dialog.component.html.template
projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__-dialog.component.scss.template
projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__-dialog.component.spec.ts.template
projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__-dialog.component.ts.template
projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__-dialog.harness.ts.template
projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__-dialog.stories.ts.template
projects/ui-schematics/schematics/components/component-for-dialog/index.ts
projects/ui-schematics/schematics/components/component-for-dialog/schema.json

**Issue**
n/a
- Add new schematics for Mat dialog 
- small harness improvement for div & span
---
```
npm install @gravitee/ui-policy-studio-angular@12.9.0-improvement-c73eed3
```
```
yarn add @gravitee/ui-policy-studio-angular@12.9.0-improvement-c73eed3
```
---
```
npm install @gravitee/ui-schematics@12.10.0-improvement-9d78975
```
```
yarn add @gravitee/ui-schematics@12.10.0-improvement-9d78975
```
---
```
npm install @gravitee/ui-particles-angular@12.10.0-improvement-9d78975
```
```
yarn add @gravitee/ui-particles-angular@12.10.0-improvement-9d78975
```
---

Add new schematics for Mat dialog & small harness improvement

---

projects/ui-particles-angular/gio-asciidoctor/gio-asciidoctor.service.ts

**Issue**
n/A
This fix error on load plugin's doc with policy studio inside APIM since 4.3
---
```
npm install @gravitee/ui-particles-angular@12.11.0-fix-9dcc649
```
```
yarn add @gravitee/ui-particles-angular@12.11.0-fix-9dcc649
```
---
```
npm install @gravitee/ui-schematics@12.11.0-fix-9dcc649
```
```
yarn add @gravitee/ui-schematics@12.11.0-fix-9dcc649
```
---

fix: error on load plugin's doc with policy studio

---

projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.html
projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.scss
projects/ui-particles-angular/src/lib/gio-form-selection-inline/gio-form-selection-inline-card.component.scss
projects/ui-particles-angular/src/lib/gio-form-selection-inline/gio-form-selection-inline.component.scss

**Issue**
https://gravitee.atlassian.net/browse/APIM-5103
fix: improve form-file-picker with long file name
fix: remove default fist left marring 
:p
---
```
npm install @gravitee/ui-schematics@12.11.2-apim-5103-e9d704d
```
```
yarn add @gravitee/ui-schematics@12.11.2-apim-5103-e9d704d
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.11.2-apim-5103-e9d704d
```
```
yarn add @gravitee/ui-policy-studio-angular@12.11.2-apim-5103-e9d704d
```
---
```
npm install @gravitee/ui-particles-angular@12.11.2-apim-5103-e9d704d
```
```
yarn add @gravitee/ui-particles-angular@12.11.2-apim-5103-e9d704d
```
---

Small improvements for form-file-picker & form-selection-inline

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/string.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/util/validation-message.util.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-5436
add pattern error message in json schema form component
---
```
npm install @gravitee/ui-particles-angular@7.59.0-apim-5436-pattern-error-message-580f329
```
```
yarn add @gravitee/ui-particles-angular@7.59.0-apim-5436-pattern-error-message-580f329
```
---

fix: add pattern error message in json schema form component

---

projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/string.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/util/validation-message.util.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-5436
Cherry pick of https://github.com/gravitee-io/gravitee-ui-particles/pull/400
---
```
npm install @gravitee/ui-policy-studio-angular@12.11.3-apim-5436-pattern-error-message-main-f042a78
```
```
yarn add @gravitee/ui-policy-studio-angular@12.11.3-apim-5436-pattern-error-message-main-f042a78
```
---
```
npm install @gravitee/ui-particles-angular@12.11.3-apim-5436-pattern-error-message-main-f042a78
```
```
yarn add @gravitee/ui-particles-angular@12.11.3-apim-5436-pattern-error-message-main-f042a78
```
---

fix: add pattern default error message

---

projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts

**Issue**
https://github.com/gravitee-io/issues/issues/5654
Init the form with default configuration's values.
---
```
npm install @gravitee/ui-schematics@12.11.4-apim-5654-ps-default-values-398653c
```
```
yarn add @gravitee/ui-schematics@12.11.4-apim-5654-ps-default-values-398653c
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.11.4-apim-5654-ps-default-values-398653c
```
```
yarn add @gravitee/ui-policy-studio-angular@12.11.4-apim-5654-ps-default-values-398653c
```
---
```
npm install @gravitee/ui-particles-angular@12.11.4-apim-5654-ps-default-values-398653c
```
```
yarn add @gravitee/ui-particles-angular@12.11.4-apim-5654-ps-default-values-398653c
```
---

feat: send policy default values on init

---

projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts

**Issue**
N/A
Allow CSS edition in monaco editor.
---
```
npm install @gravitee/ui-particles-angular@12.13.1-add-css-in-monaco-editor-ca83b42
```
```
yarn add @gravitee/ui-particles-angular@12.13.1-add-css-in-monaco-editor-ca83b42
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.13.1-add-css-in-monaco-editor-ca83b42
```
```
yarn add @gravitee/ui-policy-studio-angular@12.13.1-add-css-in-monaco-editor-ca83b42
```
---
```
npm install @gravitee/ui-schematics@12.13.1-add-css-in-monaco-editor-ca83b42
```
```
yarn add @gravitee/ui-schematics@12.13.1-add-css-in-monaco-editor-ca83b42
```
---

feat(monaco-editor): add CSS language

---

projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts

Really use full for json language
**Issue**
https://github.com/gravitee-io/issues/issues/APIM-4332
- Add auto-format on init for Monaco editor 
- small fix for PS
---
```
npm install @gravitee/ui-particles-angular@12.17.0-monac-auto-format-01238d9
```
```
yarn add @gravitee/ui-particles-angular@12.17.0-monac-auto-format-01238d9
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.17.0-monac-auto-format-01238d9
```
```
yarn add @gravitee/ui-policy-studio-angular@12.17.0-monac-auto-format-01238d9
```
---
```
npm install @gravitee/ui-schematics@12.17.0-monac-auto-format-01238d9
```
```
yarn add @gravitee/ui-schematics@12.17.0-monac-auto-format-01238d9
```
---

feat: add auto-format on init for Monaco editor

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.scss
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-5870
Fix text overflow for the 'gio-form-tags-input' component.
---
```
npm install @gravitee/ui-particles-angular@7.60.0-apim-5870-app-name-text-overflow-fix-v2-ca34b3f
```
```
yarn add @gravitee/ui-particles-angular@7.60.0-apim-5870-app-name-text-overflow-fix-v2-ca34b3f
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.60.0-apim-5870-app-name-text-overflow-fix-v2-ca34b3f
```
```
yarn add @gravitee/ui-policy-studio-angular@7.60.0-apim-5870-app-name-text-overflow-fix-v2-ca34b3f
```
---

fix: fix app name text overflow under API Plan Subscriptions

---

projects/ui-particles-angular/src/lib/gio-confirm-dialog/README.stories.mdx
projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.html
projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.ts
projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.stories.component.ts
projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.stories.ts
projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.html
projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
projects/ui-policy-studio-angular/src/lib/policy-group-studio/gio-policy-group-studio.apim.stories.ts
projects/ui-policy-studio-angular/src/lib/policy-group-studio/gio-policy-group-studio.component.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.apim.stories.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-6289
- add readOnly input for Policy Group Studio
- handle the case when policy or SPG is not found
---
```
npm install @gravitee/ui-policy-studio-angular@12.19.0-spg-readonly-1e485b0
```
```
yarn add @gravitee/ui-policy-studio-angular@12.19.0-spg-readonly-1e485b0
```
---
```
npm install @gravitee/ui-particles-angular@12.19.0-spg-readonly-e5e34c4
```
```
yarn add @gravitee/ui-particles-angular@12.19.0-spg-readonly-e5e34c4
```
---
```
npm install @gravitee/ui-schematics@12.19.0-spg-readonly-e5e34c4
```
```
yarn add @gravitee/ui-schematics@12.19.0-spg-readonly-e5e34c4
```
---

Improve: Policy Group Studio & Policy Studio

---

ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.html
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.ts
ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.stories.ts

**Issue**
To keep the same logic to avoid double-clicking, but to allow the action to be restarted. Disable button during lock period
The choice of a 2s lock was made to avoid having to implement a lock mechanism on each use of the button. and to allow a new try if the 1st is in error for example. This is classic button save behavior.
---
```
npm install @gravitee/ui-particles-angular@7.60.0-fix-save-bar-auto-lock-42967e6
```
```
yarn add @gravitee/ui-particles-angular@7.60.0-fix-save-bar-auto-lock-42967e6
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.60.0-fix-save-bar-auto-lock-42967e6
```
```
yarn add @gravitee/ui-policy-studio-angular@7.60.0-fix-save-bar-auto-lock-42967e6
```
---

fix: avoid double-clicking and disable the save/create button during lock time

---

projects/ui-particles-angular/src/lib/gio-form-headers/README.stories.mdx
projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.html
projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts

**Issue**
https://github.com/gravitee-io/issues/issues/5157
Made key autocomplete optional for table to be reused as other type than HTTP headers.
---
```
npm install @gravitee/ui-schematics@12.19.0-apim-5157-optional-autocomplete-for-form-header-61e5e7f
```
```
yarn add @gravitee/ui-schematics@12.19.0-apim-5157-optional-autocomplete-for-form-header-61e5e7f
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.19.0-apim-5157-optional-autocomplete-for-form-header-61e5e7f
```
```
yarn add @gravitee/ui-policy-studio-angular@12.19.0-apim-5157-optional-autocomplete-for-form-header-61e5e7f
```
---
```
npm install @gravitee/ui-particles-angular@12.19.0-apim-5157-optional-autocomplete-for-form-header-61e5e7f
```
```
yarn add …
```

feat: Add optional autocomplete for form header table

---

projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-5438
Avoid adding an unnecessary scrollbar
---
```
npm install @gravitee/ui-schematics@13.1.4-apim-5438-612fa60
```
```
yarn add @gravitee/ui-schematics@13.1.4-apim-5438-612fa60
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.1.4-apim-5438-612fa60
```
```
yarn add @gravitee/ui-policy-studio-angular@13.1.4-apim-5438-612fa60
```
---
```
npm install @gravitee/ui-particles-angular@13.1.4-apim-5438-612fa60
```
```
yarn add @gravitee/ui-particles-angular@13.1.4-apim-5438-612fa60
```
---

fix: when the menu is invisible, there's no need to give it a height

---

ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-5438
Avoid adding an unnecessary scrollbar
---
```
npm install @gravitee/ui-policy-studio-angular@7.60.3-7-x-apim-5438-4224107
```
```
yarn add @gravitee/ui-policy-studio-angular@7.60.3-7-x-apim-5438-4224107
```
---
```
npm install @gravitee/ui-particles-angular@7.60.3-7-x-apim-5438-4224107
```
```
yarn add @gravitee/ui-particles-angular@7.60.3-7-x-apim-5438-4224107
```
---

7.x fix: when the menu is invisible, there's no need to give it a height

---

projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts

**Issue**
na
Fix an error that makes it impossible to enter a value after deleting the previous one
---
```
npm install @gravitee/ui-particles-angular@13.3.0-fix-codeeditor-395847c
```
```
yarn add @gravitee/ui-particles-angular@13.3.0-fix-codeeditor-395847c
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.3.0-fix-codeeditor-395847c
```
```
yarn add @gravitee/ui-policy-studio-angular@13.3.0-fix-codeeditor-395847c
```
---

fix: avoid error when user clear editor value

---

projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts

**Issue**
Revert change to license service for calculating `isNativeKafka$`. The pack should not be used for evaluations.
---
```
npm install @gravitee/ui-policy-studio-angular@13.8.0-revert-is-native-kafka-changes-897596b
```
```
yarn add @gravitee/ui-policy-studio-angular@13.8.0-revert-is-native-kafka-changes-897596b
```
---
```
npm install @gravitee/ui-particles-angular@13.8.0-revert-is-native-kafka-changes-897596b
```
```
yarn add @gravitee/ui-particles-angular@13.8.0-revert-is-native-kafka-changes-897596b
```
---
```
npm install @gravitee/ui-schematics@13.8.0-revert-is-native-kafka-changes-897596b
```
```
yarn add @gravitee/ui-schematics@13.8.0-revert-is-native-kafka-changes-897596b
```
---

fix: remove isNativeKafka logic from license service

---

projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-monaco-editor.service.ts

**Issue**
---
```
npm install @gravitee/ui-policy-studio-angular@13.9.1-fix-angular19-c65ab98
```
```
yarn add @gravitee/ui-policy-studio-angular@13.9.1-fix-angular19-c65ab98
```
---
```
npm install @gravitee/ui-schematics@13.9.1-fix-angular19-c65ab98
```
```
yarn add @gravitee/ui-schematics@13.9.1-fix-angular19-c65ab98
```
---

fix: make monaco editor work with new angular version

---

projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/models/GioMonacoEditorConfig.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-language-el.service.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-language-json.service.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-monaco-editor.service.ts
projects/ui-particles-angular/src/scss/mat-override/mat-card-mdc.stories.ts
projects/ui-particles-angular/src/scss/mat-override/mat-card.scss
projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.harness.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-7958
https://gravitee.atlassian.net/browse/APIM-9285
commits : 
- A proposal to override default mat-card-title (Sync with Figma)
- PS - Fix issue when we duplicate a flow (without any change)
- issue with monaco editor and custom base path 
---
---
```
npm install @gravitee/ui-particles-angular@14.0.0-various-fixs-2151f1f
```
```
yarn add @gravitee/ui-particles-angular@14.0.0-various-fixs-2151f1f
```

Fix some issues with ui-particles

---

projects/ui-particles-angular/src/lib/gio-button-toggle-group/README.mdx
projects/ui-particles-angular/src/lib/gio-button-toggle-group/gio-button-toggle-group.scss
projects/ui-particles-angular/src/lib/gio-button-toggle-group/gio-button-toggle-group.stories.ts

**Issue**
Regarding the cloud issue, we need the `gio-button-toggle` component to display correctly with only icons.
Before:
After:
---
```
npm install @gravitee/ui-policy-studio-angular@14.0.0-improve-btn-toggle-5b36bb5
```
```
yarn add @gravitee/ui-policy-studio-angular@14.0.0-improve-btn-toggle-5b36bb5
```
---
```
npm install @gravitee/ui-schematics@14.0.0-improve-btn-toggle-5b36bb5
```
```
yarn add @gravitee/ui-schematics@14.0.0-improve-btn-toggle-5b36bb5
```
---
```
npm install @gravitee/ui-particles-angular@14.0.0-improve-btn-toggle-5b36bb5
```
```
yarn add @gravitee/ui-particles-angular@14.0.0-improve-btn-toggle-5b36bb5
```
---

fix: fix display of gio-button-toggle-group component with only icons

---

projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
projects/ui-policy-studio-angular/src/lib/models/flow/Flow.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-7958
---
```
npm install @gravitee/ui-schematics@13.12.1-13-x-fix-4e5ebb1
```
```
yarn add @gravitee/ui-schematics@13.12.1-13-x-fix-4e5ebb1
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.12.1-13-x-fix-4e5ebb1
```
```
yarn add @gravitee/ui-policy-studio-angular@13.12.1-13-x-fix-4e5ebb1
```
---
```
npm install @gravitee/ui-particles-angular@13.12.1-13-x-fix-4e5ebb1
```
```
yarn add @gravitee/ui-particles-angular@13.12.1-13-x-fix-4e5ebb1
```

fix: ps - remove id of duplicated flow

---

projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts

**Issue**
It was not possible to use `displayIf` and `gioConfig.uiType` in the same schema. 
This fix reorders how the tree is created if the `uiType` is specified.
---
```
npm install @gravitee/ui-policy-studio-angular@14.1.2-fix-ps-ui-type-map-d793575
```
```
yarn add @gravitee/ui-policy-studio-angular@14.1.2-fix-ps-ui-type-map-d793575
```
---
```
npm install @gravitee/ui-schematics@14.1.2-fix-ps-ui-type-map-d793575
```
```
yarn add @gravitee/ui-schematics@14.1.2-fix-ps-ui-type-map-d793575
```
---
```
npm install @gravitee/ui-particles-angular@14.1.2-fix-ps-ui-type-map-d793575
```
```
yarn add @gravitee/ui-particles-angular@14.1.2-fix-ps-ui-type-map-d793575
```
---

fix: keep ui type map as first field config transformation to construct tree

---

projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.scss
projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.stories.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-10167
Avoid avatar overflow with wide
---
```
npm install @gravitee/ui-particles-angular@15.2.0-fix-apim-10167-58884d1
```
```
yarn add @gravitee/ui-particles-angular@15.2.0-fix-apim-10167-58884d1
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.2.0-fix-apim-10167-58884d1
```
```
yarn add @gravitee/ui-policy-studio-angular@15.2.0-fix-apim-10167-58884d1
```
---
```
npm install @gravitee/ui-schematics@15.2.0-fix-apim-10167-58884d1
```
```
yarn add @gravitee/ui-schematics@15.2.0-fix-apim-10167-58884d1
```
---

fix: avoid avatar overflow with wide

---

projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.scss
projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.harness.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-9860
Added search box to filter flows based on name, plan name, channel name, PUB/SUB, GET/PUT, etc.
Display "No flows yet" if a plan has no flows.
---
```
npm install @gravitee/ui-particles-angular@15.3.0-apim-9860-search-flows-in-policy-studio-f12d3c2
```
```
yarn add @gravitee/ui-particles-angular@15.3.0-apim-9860-search-flows-in-policy-studio-f12d3c2
```
---
```
npm install @gravitee/ui-schematics@15.3.0-apim-9860-search-flows-in-policy-studio-f12d3c2
```
```
yarn add @gravitee/ui-schematics@15.3.0-apim-9860-search-flows-in-policy-studio-f12d3c2
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.3.0-apim-9860-search-flows-in-policy-studio-f12d3c2
```
```
yarn add …
```

APIM-9860-Search-Flows-In-Policy-Studio

---

projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/oneOfNestedGioConfigDisable.ts

see https://gravitee.atlassian.net/browse/GKO-1354
When the parent view is disabled (e.g. GKO context) the disable if makes the value of the field completely hidden.
seen with @ThibaudAV 
---
```
npm install @gravitee/ui-schematics@15.4.0-gko-1354-hidden-disabled-fields-14a4657
```
```
yarn add @gravitee/ui-schematics@15.4.0-gko-1354-hidden-disabled-fields-14a4657
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.4.0-gko-1354-hidden-disabled-fields-14a4657
```
```
yarn add @gravitee/ui-policy-studio-angular@15.4.0-gko-1354-hidden-disabled-fields-14a4657
```
---
```
npm install @gravitee/ui-particles-angular@15.4.0-gko-1354-hidden-disabled-fields-14a4657
```
```
yarn add @gravitee/ui-particles-angular@15.4.0-gko-1354-hidden-disabled-fields-14a4657
```
---

fix: make nested gio config disabled fields visible

---

projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.ts
projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.stories.ts
projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
projects/ui-particles-angular/src/lib/gio-monaco-editor/models/GioMonacoEditorConfig.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-9948
Fix issue with monaco editor and custom base path
---
```
npm install @gravitee/ui-policy-studio-angular@13.12.3-apim-9948-resolver-parameter-for-jwt-plan-not-accessible-6992158
```
```
yarn add @gravitee/ui-policy-studio-angular@13.12.3-apim-9948-resolver-parameter-for-jwt-plan-not-accessible-6992158
```
---
```
npm install @gravitee/ui-schematics@13.12.3-apim-9948-resolver-parameter-for-jwt-plan-not-accessible-6992158
```
```
yarn add @gravitee/ui-schematics@13.12.3-apim-9948-resolver-parameter-for-jwt-plan-not-accessible-6992158
```
---
```
npm install @gravitee/ui-particles-angular@13.12.3-apim-9948-resolver-parameter-for-jwt-plan-not-accessible-6992158
```
```
yarn add …
```

fix: storybook with GioMonacoEditor

---

projects/ui-particles-angular/src/lib/gio-el/gio-el.service.ts
projects/ui-particles-angular/src/lib/gio-el/index.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
projects/ui-particles-angular/src/lib/gio-form-json-schema/wrappers/gio-el-helper-wrapper.component.ts

**Issue**
APIM should be able to activate or not the EL helper
---
```
npm install @gravitee/ui-schematics@15.7.1-optin-el-helper-1503133
```
```
yarn add @gravitee/ui-schematics@15.7.1-optin-el-helper-1503133
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.7.1-optin-el-helper-32ded5c
```
```
yarn add @gravitee/ui-policy-studio-angular@15.7.1-optin-el-helper-32ded5c
```
---
```
npm install @gravitee/ui-particles-angular@15.7.1-optin-el-helper-32ded5c
```
```
yarn add @gravitee/ui-particles-angular@15.7.1-optin-el-helper-32ded5c
```
---

feat: make the el helper as optin

---

projects/ui-particles-angular/src/lib/gio-form-tags-input/README.mdx
projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.html
projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.component.ts
projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.harness.ts
projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.spec.ts
projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.stories.ts

In Cockpit, this component is used to edit the sharding tags of gateways. We want to provide users with the ability to copy these tags to the clipboard by clicking on them. 
This PR simply emits an event to indicate that a tag has been clicked.
You can see small demo here: https://github.com/gravitee-io/gravitee-cockpit/pull/6090
https://gravitee.atlassian.net/browse/CJ-3402
https://gravitee.atlassian.net/browse/CJ-3255
---
```
npm install @gravitee/ui-schematics@15.8.1-click-tag-0d8451a
```
```
yarn add @gravitee/ui-schematics@15.8.1-click-tag-0d8451a
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.8.1-click-tag-0d8451a
```
```
yarn add @gravitee/ui-policy-studio-angular@15.8.1-click-tag-0d8451a
```
---
```
npm install …
```

feat: emit event on tag clicked in gio-form-tags-input

---

projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-10964
This commit addresses a UI issue in the Plan > Create Subscription pop-up where application images in the dropdown menu appeared excessively large. The oversized images caused layout distortion, inconsistent spacing, and poor usability when browsing the list of applications.
Images are now resized to uniform thumbnail dimensions and aligned properly with the text to ensure a cleaner and more consistent dropdown experience.
---
```
npm install @gravitee/ui-schematics@15.11.1-apim-10964-image-appears-too-large-inside-dropdown-menu-167c826
```
```
yarn add @gravitee/ui-schematics@15.11.1-apim-10964-image-appears-too-large-inside-dropdown-menu-167c826
```
---
```
npm install …
```

fix(console-ui): resize images in application dropdown for consistent alignment

---

projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-10964
This commit addresses a UI issue in the Plan > Create Subscription pop-up where application images in the dropdown menu appeared excessively large. The oversized images caused layout distortion, inconsistent spacing, and poor usability when browsing the list of applications.
Images are now resized to uniform thumbnail dimensions and aligned properly with the text to ensure a cleaner and more consistent dropdown experience.
---
```
npm install @gravitee/ui-particles-angular@14.2.2-apim-10964-image-appears-too-large-inside-dropdown-menu-f6e83b1
```
```
yarn add @gravitee/ui-particles-angular@14.2.2-apim-10964-image-appears-too-large-inside-dropdown-menu-f6e83b1
```
---
```
npm install …
```

fix(ui): resize images in application dropdown for consistent alignment

---

projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.ts

**Issue**
https://gravitee.atlassian.net/browse/APIM-10964
This commit addresses a UI issue in the Plan > Create Subscription pop-up where application images in the dropdown menu appeared excessively large. The oversized images caused layout distortion, inconsistent spacing, and poor usability when browsing the list of applications.
Images are now resized to uniform thumbnail dimensions and aligned properly with the text to ensure a cleaner and more consistent dropdown experience.
---
```
npm install @gravitee/ui-schematics@14.2.2-apim-10964-image-appears-too-large-inside-subscription-dropdown-menu-0d8689c
```
```
yarn add @gravitee/ui-schematics@14.2.2-apim-10964-image-appears-too-large-inside-subscription-dropdown-menu-0d8689c
```
---
```
npm …
```

fix: resize images in application dropdown for consistent alignment
