- ui-particles-angular/projects/ui-particles-angular/README.md
**Issue**
na
add feat commit to create release on npm registry
> feat: create release on npm registry

- ui-particles-angular/.storybook/preview.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.stories.ts
**Issue**
NA
- Fix: display info message only in update mode
- Doc: add some documentation around its modes and usages
> Improve save bar

- ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/stories/theme-color/gio-palettes.stories.scss
**Issue**
na
Add default space between mat-form-field
> Form field

- .circleci/config.yml
- .github/renovate.json
**Issue**
💝
edit PR message to display chromatic deployment
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-edyrvylcjm.chromatic.com)
> ci: edit PR message to display chromatic deployment

- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6892
Complete PS with missing I/O for apis usage
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-dfbpctxsen.chromatic.com)
> Complete Policy Studio with missing I/O for apis usage

- .gitignore
- ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/ng-package.json
- ui-particles-angular/projects/ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-table-light/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-table-light/gio-table-light.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-table-light/gio-table-light.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/gio-components.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/gio-fonts.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/gio-typography.scss
- yarn.lock
**Issue**
https://github.com/gravitee-io/issues/issues/6763
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-xrcwmrsaza.chromatic.com)
> feat: add gio-table-light component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.ts
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-oqhiwxlzpq.chromatic.com)
> feat(gio-save-bar): add possibility to override default css

- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-table-light/gio-table-light.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/gio-typography.scss
**Issue**
https://github.com/gravitee-io/issues/issues/6765
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-xofehaphcd.chromatic.com)
> refactor(gio-table-light): mv typo to component

- ui-particles-angular/projects/ui-particles-angular/assets/gio-icons.svg
**Issue**
NA
Added missing icons from mockups:
- arrow-left
- hand
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hjlpyhtshw.chromatic.com)
> fix: add missing icons

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-theme-variable.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-theme.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/index.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-option.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-option.stories.ts
**Issue**
https://github.com/gravitee-io/issues/issues/7149
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-dkrtxnhaeo.chromatic.com)
> Improve form headers component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.spec.ts
gravitee-io/issues#7149
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-yetgerjunk.chromatic.com)
> fix(form-headers): filter suggestions with header name

- ui-particles-angular/projects/ui-particles-angular/assets/gio-icons.svg
**Issue**
NA
I added missing icons to the icons sprite
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-taowrxqoiw.chromatic.com)
> Adding missing icons

- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.stories.ts
**Issue**
N.A.
Add `cursor: not-allowed` on disabled mat-form-fields
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-ydpsfrazbh.chromatic.com)
> feat: add cursor not allowed on disabled form field

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.html
**Issue**
NA
Remove extra info text in info banner
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-zzzhsygdlx.chromatic.com)
> Banner: Remove extra info text in info banner

- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts
**Issue**
N.A. 
Fix wrong section name on mat-button story
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-klsqnptlli.chromatic.com)
> chore: fix section title for stroke buttons

- .circleci/config.yml
chore: update all secrethub with keeper command
secrethub orb will not be used any more and has to be replaced with keeper
Updated keeper orb and keeper urls in the jobs
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-lrdlfwsjrt.chromatic.com)
> chore: update all secrethub with keeper command

- ui-particles-angular/package.json
- ui-particles-angular/projects/ui-policy-studio-angular/package.json
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/ConfigurationSchema.fixture.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/testing/stories-resources/apim-definition.json
- yarn.lock
**Issue**
gravitee-io/issues#7625
Following the changes of the issue. Here is a pr to update the ui component and the flow_mode.
Here I changed the flow mode value in the apim definition json file. Today on the main branch we have _best_match_ as value but the select value is default.
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-qpwgsjoaxe.chromatic.com)
> fix: flow mode

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/gio-form-tags-input.module.spec.ts
**Issue**
n/a
add isDisabled() to GioFormTagsInputHarness to use it in apim test
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-lfgpcagmvs.chromatic.com)
> feat(angular): add isDisabled() to GioFormTagsInputHarness

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.spec.ts
**Issue**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-qyrpvevjjk.chromatic.com)
> feat(angular): add simple addHeader to GioFormHeadersHarness

- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
**Issue**
https://github.com/gravitee-io/issues/issues/8141
add readonly input for Policy studio
> feat(ps): add readonly input  for Policy studio

- ui-particles-angular/projects/ui-particles-angular/assets/gio-icons.svg
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-wqznhnedde.chromatic.com)
> fix: add usefull icons

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-add-button/gio-form-file-picker-add-button.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-empty/gio-form-file-picker-empty.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker-empty/gio-form-file-picker-empty.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.model.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-file-picker/gio-form-file-picker.stories.ts
**Issue**
n/a
- allow to change the add-button size
- directly return base64 file in NewFile instance
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-untizchmgl.chromatic.com)
> feat: improve gio-form-file-picker

- ui-particles-angular/.storybook/main.ts
- ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/src/scss/gio-mat-palettes.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/index.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/color/gio-palettes.stories.scss
- yarn.lock
APIM-102
**Issue**
https://graviteecommunity.atlassian.net/jira/software/c/projects/APIM/boards/2?modal=detail&selectedIssue=APIM-102&sprint=10
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-xhxmczhfei.chromatic.com)
> feat: udpate all colors with perseverance

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/index.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.module.ts
apim-225
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-dcupnxdujw.chromatic.com)
> feat(menu): improve the reduce mode

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-subitem/gio-submenu-subitem.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-subitem/gio-submenu-subitem.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
APIM-226
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-ilyierayhf.chromatic.com)
> feat(menu): implement keyboard nav 

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-subitem/gio-submenu-subitem.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
APIM-225
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-vhtgxybhbh.chromatic.com)
> fix(menu): improve submenu 

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-footer/gio-menu-footer.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-list/gio-menu-list.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-item/gio-submenu-item.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-subitem/gio-submenu-subitem.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
**Issue**
APIM-271
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-nvefnjbajg.chromatic.com)
> fix(menu): set z-index only when submenu overlay mode

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-footer/gio-menu-footer.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-footer/gio-menu-footer.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-header/gio-menu-header.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-list/gio-menu-list.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-group/gio-submenu-group.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-item/gio-submenu-item.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-item/gio-submenu-item.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-item/gio-submenu-item.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-subitem/gio-submenu-subitem.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/index.ts
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-271
- shrink the width of the menu in reduced mode
- add space around the title in the menu footer
- don't change background in submenu item when hovering while active
- create a submenu group component to allow grouping subitems. It allows to have both single links and group of links into a category
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-phqhjkbpuj.chromatic.com)
> improve menu style

- ui-particles-angular/projects/ui-particles-angular/assets/gio-icons.svg
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-icons/gio-icons.spec.ts
APIM-228
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-jazbmhodtq.chromatic.com)
> feat: update icons

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-content/gio-top-bar-content.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-content/gio-top-bar-content.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-content/gio-top-bar-content.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-link/gio-top-bar-link.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-link/gio-top-bar-link.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-link/gio-top-bar-link.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-link/gio-top-bar-link.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-menu/gio-top-bar-menu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-menu/gio-top-bar-menu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-menu/gio-top-bar-menu.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar-menu/gio-top-bar-menu.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/gio-top-bar.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-top-bar/index.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-301
Creation of a top bar component
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-dcgboagjln.chromatic.com)
> feat(top-bar): create a top-bar component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
> fix(submenu): resolve dynamic height

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-button/REAMDE.stories.mdx
I added some description for the button usage
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-dkmwlkcepm.chromatic.com)
> docs: add readme for button usage

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-link/gio-link.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-link/gio-link.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/index.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/gio-typography.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/showcase-typography.component.html
https://graviteecommunity.atlassian.net/browse/APIM-257
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hjgvvrimfc.chromatic.com)
> feat(banner): improve banner with perseverance design

- ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/__snapshots__/gio-avatar.component.spec.ts.snap
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/gio-avatar.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-avatar/index.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
- yarn.lock
**Issue**
N.A.
Add avatar component (will me moved out of APIM code when merged)
**Screenshot**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-uvrjepixon.chromatic.com)
> feat: add avatar component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.ts
**Issue**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-avubnghtij.chromatic.com)
> fix(gio-save-bar): prevent multiple submit

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-save-bar/gio-save-bar.module.spec.ts
**Issue**
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-trpxrkftup.chromatic.com)
> fix(gio-save-bar): deal with timer in submit handler

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.stories.ts
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-393
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-oqwesxfxqu.chromatic.com)
> fix(gio-menu): resolve submenu position

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-393
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-ukfvbkpakq.chromatic.com)
> fix(gv-menu): improve overlay menu position

- .circleci/config.yml
**Issue**
NA
Remove usage of `gravitee-qa` as env variables are already contained in `cicd-orchestrator`
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-smahkoumos.chromatic.com)
> Update CircleCI context used in config.yml

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-item/gio-menu-item.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu-item/gio-submenu-item.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-291
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-voxotcraiz.chromatic.com)
> feat(gio-menu): add keyboard accessibility in collapse mode

- .circleci/config.yml
Security fix
---
```
npm install @gravitee/ui-policy-studio-angular@5.1.0-devops-50-cci-use-ksm-1db3f0c
```
```
yarn add @gravitee/ui-policy-studio-angular@5.1.0-devops-50-cci-use-ksm-1db3f0c
```
---
> feat(CI): get chromatic token from keeper

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/entrypoints.ts
**Issue**
n/a
Just add Input | preview display 
---
```
npm install @gravitee/ui-particles-angular@5.1.0-fjs-simple-c25e1a5
```
```
yarn add @gravitee/ui-particles-angular@5.1.0-fjs-simple-c25e1a5
```
---
> chore: improve story for gio-form-json-schema

- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-input.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-588
New story to show all the different input types present in the [design system](https://www.figma.com/file/okDdv0Rs884yxKgXQROqaG/Perseverance-design-system?node-id=1613%3A1165)
---
```
npm install @gravitee/ui-particles-angular@5.1.0-add-input-stories-8d55698
```
```
yarn add @gravitee/ui-particles-angular@5.1.0-add-input-stories-8d55698
```
---
> Add input stories

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-breadcrumb/gio-breadcrumb.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-breadcrumb/gio-breadcrumb.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-input.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-302
---
> fix(gio-breadcrumb): fix styles

- ui-particles-angular/.storybook/preview.ts
- ui-particles-angular/projects/ui-particles-angular/src/2-GetStarted.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-mat-config/gio-mat-config.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-mat-config/index.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu-selector/gio-menu-selector.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-form-field.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-input.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-456
---
```
npm install @gravitee/ui-particles-angular@5.1.4-apply-form-field-appearance-54a6c3c
```
```
yarn add @gravitee/ui-particles-angular@5.1.4-apply-form-field-appearance-54a6c3c
```
---
> feat: add gio-config module with form field appearance

- ui-particles-angular/projects/ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-451
---
---
```
npm install @gravitee/ui-particles-angular@5.3.0-apim-451-conf-options-entrypoint-209b5b9
```
```
yarn add @gravitee/ui-particles-angular@5.3.0-apim-451-conf-options-entrypoint-209b5b9
```
> feat: export gio-form-json-schema component

- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-input.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-588
Add select in input story
---
```
npm install @gravitee/ui-particles-angular@5.5.0-add-select-in-input-story-7f9544f
```
```
yarn add @gravitee/ui-particles-angular@5.5.0-add-select-in-input-story-7f9544f
```
---
> feat: add select in input story

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss
**Issue**
https://github.com/gravitee-io/issues/issues/8867
[gravitee.atlassian.net/browse/APIM-779](https://gravitee.atlassian.net/browse/APIM-779)
Backport https://github.com/gravitee-io/gravitee-ui-particles/pull/202 on `4.x`
---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-udixahmxuq.chromatic.com)
> Display multiple spaces properly in Confirm and Validate dialog #202

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/allOf.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/enum.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/oneOf.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/references.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/securityConfig.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/multischema-type.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/multischema-type.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/object-type.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/object-type.component.ts
**Issue**
n/a
Add more complex exemple with json schema
---
```
npm install @gravitee/ui-policy-studio-angular@5.7.3-json-schema-d2114c2
```
```
yarn add @gravitee/ui-policy-studio-angular@5.7.3-json-schema-d2114c2
```
---
> Add some json-schema example

- .circleci/config.yml
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-label.directive.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-slide-toggle.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-slide-toggle.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-slide-toggle.component.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-slide-toggle.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-slide-toggle.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-slide-toogle/gio-form-slide-toggle.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-tags-input/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-927
---
```
npm install @gravitee/ui-particles-angular@5.9.0-slide-toggle-bfd7539
```
```
yarn add @gravitee/ui-particles-angular@5.9.0-slide-toggle-bfd7539
```
---
> Slide toggle

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.directive.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/multischema-type.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/object-type.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
n/a
Migrated from apim. will be used in good quality apim forms
---
```
npm install @gravitee/ui-particles-angular@5.11.0-focus-invalid-7cb626b
```
```
yarn add @gravitee/ui-particles-angular@5.11.0-focus-invalid-7cb626b
```
---
> Form Focus on first invalid

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/kafka-advanced.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/object-type.component.scss
**Issue**
https://gravitee.atlassian.net/browse/APIM-927
Add showcase for kafka advanced with pretty Ui
---
```
npm install @gravitee/ui-policy-studio-angular@5.11.0-kafka-a-8dc750c
```
```
yarn add @gravitee/ui-policy-studio-angular@5.11.0-kafka-a-8dc750c
```
---
> Add showcase for kafka-advanced 

- .circleci/config.yml
- ui-particles-angular/.storybook/main.ts
- ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.json
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/object-type.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.testing.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/models/GioMonacoEditorConfig.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/models/MonacoEditorTheme.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-language-json.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-monaco-editor.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
- yarn.lock
**Issue**
n/a not directly
1st pr for this component. it remains simple for the moment its goal will be to be used to create the JsonSchem for the plugin
---
```
npm install @gravitee/ui-particles-angular@5.13.0-monaco-editor-7a6cb04
```
```
yarn add @gravitee/ui-particles-angular@5.13.0-monaco-editor-7a6cb04
```
---
```
npm install @gravitee/ui-policy-studio-angular@5.13.0-monaco-editor-7a6cb04
```
```
yarn add @gravitee/ui-policy-studio-angular@5.13.0-monaco-editor-7a6cb04
```
---
> Add Monaco editor component

- ui-particles-angular/package.json
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- yarn.lock
**Issue**
https://gravitee.atlassian.net/browse/APIM-740
Improve Online JsonSchema tester with 
- Monaco code editor
- Error validation like rest-api with AJV 
- Initial Payload editable
- Output Payload readonly
---
```
npm install @gravitee/ui-particles-angular@5.14.0-improve-json-schema-preview-7fe3956
```
```
yarn add @gravitee/ui-particles-angular@5.14.0-improve-json-schema-preview-7fe3956
```
---
```
npm install @gravitee/ui-policy-studio-angular@5.14.0-improve-json-schema-preview-6cb9b1c
```
```
yarn add @gravitee/ui-policy-studio-angular@5.14.0-improve-json-schema-preview-6cb9b1c
```
---
> Improve json schema preview

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/http-proxy.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1105
---
```
npm install @gravitee/ui-particles-angular@5.15.0-showcase-http-proxy-fa50d15
```
```
yarn add @gravitee/ui-particles-angular@5.15.0-showcase-http-proxy-fa50d15
```
---
```
npm install @gravitee/ui-policy-studio-angular@5.15.0-showcase-http-proxy-fa50d15
```
```
yarn add @gravitee/ui-policy-studio-angular@5.15.0-showcase-http-proxy-fa50d15
```
---
> feat: add http-proxy schema form

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/testing-json-schema/webhook-advanced.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1111
---
```
npm install @gravitee/ui-policy-studio-angular@5.16.0-showcase-webhook-advanced-71fe274
```
```
yarn add @gravitee/ui-policy-studio-angular@5.16.0-showcase-webhook-advanced-71fe274
```
---
```
npm install @gravitee/ui-particles-angular@5.16.0-showcase-webhook-advanced-71fe274
```
```
yarn add @gravitee/ui-particles-angular@5.16.0-showcase-webhook-advanced-71fe274
```
---
> feat: add webhook-advanced schema form

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-loader/gio-loader.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-loader/gio-loader.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-loader/gio-loader.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-loader/gio-loader.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-loader/gio-loader.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1135
Create component for loader
---
```
npm install @gravitee/ui-policy-studio-angular@5.18.0-apim-1135-loader-a165d52
```
```
yarn add @gravitee/ui-policy-studio-angular@5.18.0-apim-1135-loader-a165d52
```
---
```
npm install @gravitee/ui-particles-angular@5.18.0-apim-1135-loader-755e2f3
```
```
yarn add @gravitee/ui-particles-angular@5.18.0-apim-1135-loader-755e2f3
```
---
> Apim 1135 loader

- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-caption-2/gio-caption-2.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-caption-2/gio-caption-2.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/gio-typography.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/theme/typography/showcase-typography.component.html
Issue
https://gravitee.atlassian.net/browse/APIM-591
Description
Update neutral badge
Add new caption-2 typo
---
```
npm install @gravitee/ui-policy-studio-angular@5.22.0-apim-591-updates-5b0d8d6
```
```
yarn add @gravitee/ui-policy-studio-angular@5.22.0-apim-591-updates-5b0d8d6
```
---
```
npm install @gravitee/ui-particles-angular@5.22.0-apim-591-updates-5b0d8d6
```
```
yarn add @gravitee/ui-particles-angular@5.22.0-apim-591-updates-5b0d8d6
```
---
> update badge and add caption-2 typo

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-icons/gio-icons.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.model.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/ConnectorsInfo.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/index-testing.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/index.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/plan/Plan.fixture.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/plan/Plan.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/plan/index-testing.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/plan/index.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/public-api.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/testing/harnesses/div.harness.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1549
- Add Ui for left flows menu
- Add selection mechanism
---
```
npm install @gravitee/ui-particles-angular@7.1.0-apim-1549-flows-list-54b2c17
```
```
yarn add @gravitee/ui-particles-angular@7.1.0-apim-1549-flows-list-54b2c17
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.1.0-apim-1549-flows-list-54b2c17
```
```
yarn add @gravitee/ui-policy-studio-angular@7.1.0-apim-1549-flows-list-54b2c17
```
---
> Policy Studio : impl flows menu

- ui-particles-angular/projects/ui-particles-angular/src/scss/component/gio-badge/gio-badge.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.component.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/gio-ps-flow-form-dialog.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.model.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/index.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1550
Add Output to send whit changes to save when the user Save
---
```
npm install @gravitee/ui-policy-studio-angular@7.4.0-apim-1550-save-output-7fb96a0
```
```
yarn add @gravitee/ui-policy-studio-angular@7.4.0-apim-1550-save-output-7fb96a0
```
---
```
npm install @gravitee/ui-particles-angular@7.4.0-apim-1550-save-output-7fb96a0
```
```
yarn add @gravitee/ui-particles-angular@7.4.0-apim-1550-save-output-7fb96a0
```
---
> Policy studio - Impl save button  

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.component.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1832
> fix(gio-submenu): add detectChanges after observables

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
**Issue**
n/a
i hope this time is good
---
```
npm install @gravitee/ui-policy-studio-angular@7.17.2-fix-ps-4c96f71
```
```
yarn add @gravitee/ui-policy-studio-angular@7.17.2-fix-ps-4c96f71
```
---
```
npm install @gravitee/ui-particles-angular@7.17.2-fix-ps-4c96f71
```
```
yarn add @gravitee/ui-particles-angular@7.17.2-fix-ps-4c96f71
```
---
> fix(json-schema): json-schema reorder code on init

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/code-editor-type.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-info-bar/gio-ps-flow-details-info-bar.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-info-bar/gio-ps-flow-details-info-bar.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-info-bar/gio-ps-flow-details-info-bar.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.module.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
**Issue**
https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/APIM-2085
Small improvement to complete Policy studio UI/UX
---
```
npm install @gravitee/ui-policy-studio-angular@7.19.0-policy-studio-step-8-88b050f
```
```
yarn add @gravitee/ui-policy-studio-angular@7.19.0-policy-studio-step-8-88b050f
```
---
```
npm install @gravitee/ui-particles-angular@7.19.0-policy-studio-step-8-88b050f
```
```
yarn add @gravitee/ui-particles-angular@7.19.0-policy-studio-step-8-88b050f
```
---
> Policy studio UI/UX improvement

- ui-particles-angular/projects/ui-particles-angular/testing/harnesses/div.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.apim.stories.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/models/flow/Flow.fixture.ts
**Issue**
https://gravitee.atlassian.net/jira/software/c/projects/APIM/issues/APIM-2085
impl condition for flow and step
---
```
npm install @gravitee/ui-particles-angular@7.20.0-policy-studio-step-8-a5c365e
```
```
yarn add @gravitee/ui-particles-angular@7.20.0-policy-studio-step-8-a5c365e
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.20.0-policy-studio-step-8-a5c365e
```
```
yarn add @gravitee/ui-policy-studio-angular@7.20.0-policy-studio-step-8-a5c365e
```
---
> Policy studio - Condition for flow and step

- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-2085
n/a
---
```
npm install @gravitee/ui-policy-studio-angular@7.23.0-policy-studio-step-9-9cd6657
```
```
yarn add @gravitee/ui-policy-studio-angular@7.23.0-policy-studio-step-9-9cd6657
```
---
> fix: improved a few things to have better UX

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-icon.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-icon.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-wrapper.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-wrapper.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.base.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-icons/gio-icons.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-2085
Add Clipboard component
Fix disabled console error on json-schema component 
---
```
npm install @gravitee/ui-policy-studio-angular@7.23.1-policy-studio-step-9-0cee879
```
```
yarn add @gravitee/ui-policy-studio-angular@7.23.1-policy-studio-step-9-0cee879
```
---
```
npm install @gravitee/ui-particles-angular@7.23.1-policy-studio-step-9-0cee879
```
```
yarn add @gravitee/ui-particles-angular@7.23.1-policy-studio-step-9-0cee879
```
---
> Policy studio fixe and 

- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.service.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-2085
`
n/a
---
```
npm install @gravitee/ui-policy-studio-angular@7.24.0-policy-studio-step-9-ff9d210
```
```
yarn add @gravitee/ui-policy-studio-angular@7.24.0-policy-studio-step-9-ff9d210
```
---
```
npm install @gravitee/ui-particles-angular@7.24.0-policy-studio-step-9-ff9d210
```
```
yarn add @gravitee/ui-particles-angular@7.24.0-policy-studio-step-9-ff9d210
```
---
> fix: improve Policy Studio on some unexpected behaviour

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-2122
I don't know if I should add a test. this is a special case. 
---
```
npm install @gravitee/ui-policy-studio-angular@7.24.1-fix-json-schema-7bea8bb
```
```
yarn add @gravitee/ui-policy-studio-angular@7.24.1-fix-json-schema-7bea8bb
```
---
```
npm install @gravitee/ui-particles-angular@7.24.1-fix-json-schema-7bea8bb
```
```
yarn add @gravitee/ui-particles-angular@7.24.1-fix-json-schema-7bea8bb
```
---
> fix: error with custom array header

- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1560
disable or enable a step in a flow
https://github.com/gravitee-io/gravitee-ui-particles/assets/25704259/a7c4573f-679b-406a-9271-4f37db7b9425
---
```
npm install @gravitee/ui-policy-studio-angular@7.25.0-apim-1560-disable-step-85be809
```
```
yarn add @gravitee/ui-policy-studio-angular@7.25.0-apim-1560-disable-step-85be809
```
---
```
npm install @gravitee/ui-particles-angular@7.25.0-apim-1560-disable-step-85be809
```
```
yarn add @gravitee/ui-particles-angular@7.25.0-apim-1560-disable-step-85be809
```
---
> feat: disable or enable a step in a flow

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-button-toggle-group/gio-button-toggle-group.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.adapter.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.adapter.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.module.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-submenu/gio-submenu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-input.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-table.stories.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-execution-form-dialog/gio-ps-flow-execution-form-dialog.stories.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-message-form-dialog/gio-ps-flow-message-form-dialog.stories.ts
**Issue**
Par of https://gravitee.atlassian.net/browse/APIM-2363
Continue new Cron component.  It's now Ok to play with it (cc @phiz71 )
Next Use it in APIM 
Fimga inspiration : https://www.figma.com/file/okDdv0Rs884yxKgXQROqaG/Particles-design-system?node-id=7545%3A15811&mode=dev
---
```
npm install @gravitee/ui-policy-studio-angular@7.31.0-form-cron-p2-9b7787b
```
```
yarn add @gravitee/ui-policy-studio-angular@7.31.0-form-cron-p2-9b7787b
```
---
```
npm install @gravitee/ui-particles-angular@7.31.0-form-cron-p2-9b7787b
```
```
yarn add @gravitee/ui-particles-angular@7.31.0-form-cron-p2-9b7787b
```
---
> Finish new form cron component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license-dialog/gio-license-dialog.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license-dialog/gio-license-dialog.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts
**Issue**
---
```
npm install @gravitee/ui-particles-angular@7.33.0-coc-446-sso-menu-account-settings-b1c7fa3
```
```
yarn add @gravitee/ui-particles-angular@7.33.0-coc-446-sso-menu-account-settings-b1c7fa3
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.33.0-coc-446-sso-menu-account-settings-b1c7fa3
```
```
yarn add @gravitee/ui-policy-studio-angular@7.33.0-coc-446-sso-menu-account-settings-b1c7fa3
```
---
> feat(license): improve custom dialog

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron-hint.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron-label.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.module.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-focus-first-invalid/gio-form-focus-first-invalid.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
n/a
add label in front of the border it's to hard 😁 
And some final touche fix
In place : 
---
```
npm install @gravitee/ui-policy-studio-angular@7.34.0-form-cron-p2-cb17759
```
```
yarn add @gravitee/ui-policy-studio-angular@7.34.0-form-cron-p2-cb17759
```
---
```
npm install @gravitee/ui-particles-angular@7.34.0-form-cron-p2-cb17759
```
```
yarn add @gravitee/ui-particles-angular@7.34.0-form-cron-p2-cb17759
```
---
> feat: cron-form - add label & hint like material form field

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.scss
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.harness.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/gio-policy-studio.spec.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-2834
Improve UX for main save button and catalog save button.
Improve Json-Form component to set default json-schema value without any formControl event and add ready output
For catalog improvement : 
---
```
npm install @gravitee/ui-particles-angular@7.36.0-fix-ps-v2-e422f7b
```
```
yarn add @gravitee/ui-particles-angular@7.36.0-fix-ps-v2-e422f7b
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.36.0-fix-ps-v2-e422f7b
```
```
yarn add @gravitee/ui-policy-studio-angular@7.36.0-fix-ps-v2-e422f7b
```
---
> Policy-Studio: Fix & improvement

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-asciidoctor/gio-asciidoctor.stories.ts
Fix storybook deployment
---
```
npm install @gravitee/ui-particles-angular@7.37.4-fix-storybook-b2f21f4
```
```
yarn add @gravitee/ui-particles-angular@7.37.4-fix-storybook-b2f21f4
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.37.4-fix-storybook-b2f21f4
```
```
yarn add @gravitee/ui-policy-studio-angular@7.37.4-fix-storybook-b2f21f4
```
---
> refactor: update asciidoctor story

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-icon.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-icon.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-wrapper.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard-copy-wrapper.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.base.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-clipboard/gio-clipboard.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/COC-478
---
```
npm install @gravitee/ui-policy-studio-angular@7.37.4-coc-478-sso-design-fc1e9b2
```
```
yarn add @gravitee/ui-policy-studio-angular@7.37.4-coc-478-sso-design-fc1e9b2
```
---
```
npm install @gravitee/ui-particles-angular@7.37.4-coc-478-sso-design-fc1e9b2
```
```
yarn add @gravitee/ui-particles-angular@7.37.4-coc-478-sso-design-fc1e9b2
```
---
> feat: improve a11y on clipboard components

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-banner/gio-banner.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers-label.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-table-light/gio-table-light.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-table-light/gio-table-light.stories.ts
**Issue**
n/a
- Improve form-headers disabled display
- Improve form-cron disabled display
- Add collapsible mode for banner
---
```
npm install @gravitee/ui-policy-studio-angular@7.38.1-improvement-9d90b42
```
```
yarn add @gravitee/ui-policy-studio-angular@7.38.1-improvement-9d90b42
```
---
```
npm install @gravitee/ui-particles-angular@7.38.1-improvement-9d90b42
```
```
yarn add @gravitee/ui-particles-angular@7.38.1-improvement-9d90b42
```
---
> Various Improvement

- .github/CODEOWNERS
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-badge/gio-badge.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-headers/gio-form-headers.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor-form-field.directive.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.testing.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
n/a
- small fix on icon inside badge
- missing export component
- change CODEOWNER
---
```
npm install @gravitee/ui-particles-angular@7.39.0-fix-badge-a6237ca
```
```
yarn add @gravitee/ui-particles-angular@7.39.0-fix-badge-a6237ca
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.39.0-fix-badge-379e056
```
```
yarn add @gravitee/ui-policy-studio-angular@7.39.0-fix-badge-379e056
```
---
> Various improvement 

- ui-particles-angular/.storybook/preview.ts
- ui-particles-angular/projects/ui-particles-angular/src/stories/oem-theme/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/stories/oem-theme/oem-theme-menu-and-top-bar.stories.ts
**Issue**
https://github.com/gravitee-io/issues/issues/3112
- Create a view of menu + top bar for oem customization
- Add a folder for all oem theme information
---
```
npm install @gravitee/ui-policy-studio-angular@7.39.0-apim-3112-create-oem-menu-story-d1b7b97
```
```
yarn add @gravitee/ui-policy-studio-angular@7.39.0-apim-3112-create-oem-menu-story-d1b7b97
```
---
```
npm install @gravitee/ui-particles-angular@7.39.0-apim-3112-create-oem-menu-story-d1b7b97
```
```
yarn add @gravitee/ui-particles-angular@7.39.0-apim-3112-create-oem-menu-story-d1b7b97
```
---
> Apim 3112 create oem menu + top bar story

- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/README.stories.mdx
**Issue**
https://gravitee.atlassian.net/browse/APIM-3537
Update text to match what is customizable via Storybook.
---
```
npm install @gravitee/ui-policy-studio-angular@7.50.0-apim-3537-update-oem-read-me-cba6c23
```
```
yarn add @gravitee/ui-policy-studio-angular@7.50.0-apim-3537-update-oem-read-me-cba6c23
```
---
```
npm install @gravitee/ui-particles-angular@7.50.0-apim-3537-update-oem-read-me-cba6c23
```
```
yarn add @gravitee/ui-particles-angular@7.50.0-apim-3537-update-oem-read-me-cba6c23
```
---
> doc: update read me for oem customization

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.stories.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-and-validate-dialog/gio-confirm-and-validate-dialog.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.stories.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-confirm-dialog/gio-confirm-dialog.stories.ts
**Issue**
https://gravitee.atlassian.net/browse/CJ-816
---
```
npm install @gravitee/ui-particles-angular@7.50.0-improve-dialogs-3d4f9f9
```
```
yarn add @gravitee/ui-particles-angular@7.50.0-improve-dialogs-3d4f9f9
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.50.0-improve-dialogs-3d4f9f9
```
```
yarn add @gravitee/ui-policy-studio-angular@7.50.0-improve-dialogs-3d4f9f9
```
---
>  feat: improve content part for dialogs

- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
Forgot to export it the first time 🙈 
Exporting the component so that it can be used in APIM
---
```
npm install @gravitee/ui-policy-studio-angular@7.55.0-apim-3663-export-component-96c3e8d
```
```
yarn add @gravitee/ui-policy-studio-angular@7.55.0-apim-3663-export-component-96c3e8d
```
---
```
npm install @gravitee/ui-particles-angular@7.55.0-apim-3663-export-component-96c3e8d
```
```
yarn add @gravitee/ui-particles-angular@7.55.0-apim-3663-export-component-96c3e8d
```
---
> chore: export gio license expiration notification

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.spec.ts
**Issue**
https://gravitee.atlassian.net/browse/AM-2140
https://gravitee.atlassian.net/browse/APIM-3751
---
```
npm install @gravitee/ui-particles-angular@7.57.0-fix-am-2140-bf42736
```
```
yarn add @gravitee/ui-particles-angular@7.57.0-fix-am-2140-bf42736
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.57.0-fix-am-2140-bf42736
```
```
yarn add @gravitee/ui-policy-studio-angular@7.57.0-fix-am-2140-bf42736
```
---
> fix: am-2140 contact link in notification banner

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license-expiration-notification/gio-license-expiration-notification.component.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-3748
---
```
npm install @gravitee/ui-policy-studio-angular@7.57.0-feat-apim-3748-08f52b8
```
```
yarn add @gravitee/ui-policy-studio-angular@7.57.0-feat-apim-3748-08f52b8
```
---
```
npm install @gravitee/ui-particles-angular@7.57.0-feat-apim-3748-08f52b8
```
```
yarn add @gravitee/ui-particles-angular@7.57.0-feat-apim-3748-08f52b8
```
---
> feat: apim-3748 notification banner when expire today

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-badge/gio-badge.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-badge/gio-badge.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-button.scss
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-card-mdc.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/scss/mat-override/mat-card.scss
**Issue**
n/a
As i work on angular 15 migration to AM i see somes small fix ;)
---
```
npm install @gravitee/ui-particles-angular@9.0.2-ui-fix-from-am-83ce1ab
```
```
yarn add @gravitee/ui-particles-angular@9.0.2-ui-fix-from-am-83ce1ab
```
---
```
npm install @gravitee/ui-policy-studio-angular@9.0.2-ui-fix-from-am-83ce1ab
```
```
yarn add @gravitee/ui-policy-studio-angular@9.0.2-ui-fix-from-am-83ce1ab
```
---
> Small Ui Improvement

- .circleci/config.yml
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.component.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.harness.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.service.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/index.ts
add `gio-search-menu` component for the side nav
---
```
npm install @gravitee/ui-particles-angular@9.2.0-apim-3442-menu-search-ecbb5ef
```
```
yarn add @gravitee/ui-particles-angular@9.2.0-apim-3442-menu-search-ecbb5ef
```
---
```
npm install @gravitee/ui-policy-studio-angular@9.2.0-apim-3442-menu-search-ecbb5ef
```
```
yarn add @gravitee/ui-policy-studio-angular@9.2.0-apim-3442-menu-search-ecbb5ef
```
---
> feat: init gio-search-menu component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/gio-card-empty-state.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/gio-card-empty-state.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/gio-card-empty-state.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/gio-card-empty-state.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/gio-card-empty-state.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-card-empty-state/index.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu-search/gio-menu-search.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/public-api.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-1427
add gio-empty-state component
---
```
npm install @gravitee/ui-policy-studio-angular@9.4.1-apim-1427-empty-state-66325a7
```
```
yarn add @gravitee/ui-policy-studio-angular@9.4.1-apim-1427-empty-state-66325a7
```
---
```
npm install @gravitee/ui-particles-angular@9.4.1-apim-1427-empty-state-66325a7
```
```
yarn add @gravitee/ui-particles-angular@9.4.1-apim-1427-empty-state-66325a7
```
---
> feat: add gio-empty-state component

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts
**Issue**
---
```
npm install @gravitee/ui-policy-studio-angular@10.1.0-fix-license-service-d6f0b5e
```
```
yarn add @gravitee/ui-policy-studio-angular@10.1.0-fix-license-service-d6f0b5e
```
---
```
npm install @gravitee/ui-particles-angular@10.1.0-fix-license-service-d6f0b5e
```
```
yarn add @gravitee/ui-particles-angular@10.1.0-fix-license-service-d6f0b5e
```
---
> feat: manage Plugin in license directive 

- .circleci/config.yml
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.spec.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.directive.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-license/gio-license.service.ts
**Issue**
---
```
npm install @gravitee/ui-policy-studio-angular@9.6.0-fix-license-direc-8298ebd
```
```
yarn add @gravitee/ui-policy-studio-angular@9.6.0-fix-license-direc-8298ebd
```
---
```
npm install @gravitee/ui-particles-angular@9.6.0-fix-license-direc-8298ebd
```
```
yarn add @gravitee/ui-particles-angular@9.6.0-fix-license-direc-8298ebd
```
---
>  fix: manage Plugin in license directive

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/kafka-advanced.ts
- ui-particles-angular/projects/ui-policy-studio-angular/package.json
**Issue**
part of https://gravitee.atlassian.net/browse/APIM-3969
When formly is initialised, it emits several values as it builds up little by little. The control value must therefore be kept synchronised. Sync is stopped when the component is ready.
---
```
npm install @gravitee/ui-policy-studio-angular@12.0.1-fix-json-schema-dd748ed
```
```
yarn add @gravitee/ui-policy-studio-angular@12.0.1-fix-json-schema-dd748ed
```
---
```
npm install @gravitee/ui-particles-angular@12.0.1-fix-json-schema-dd748ed
```
```
yarn add @gravitee/ui-particles-angular@12.0.1-fix-json-schema-dd748ed
```
---
> Fix json schema

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.html
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-cron/gio-form-cron.component.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/string.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/cron-type.component.ts
**Issue**
---
```
npm install @gravitee/ui-schematics@12.2.0-apim-3797-cron-ebff4c7
```
```
yarn add @gravitee/ui-schematics@12.2.0-apim-3797-cron-ebff4c7
```
---
```
npm install @gravitee/ui-particles-angular@12.2.0-apim-3797-cron-ebff4c7
```
```
yarn add @gravitee/ui-particles-angular@12.2.0-apim-3797-cron-ebff4c7
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.2.0-apim-3797-cron-ebff4c7
```
```
yarn add @gravitee/ui-policy-studio-angular@12.2.0-apim-3797-cron-ebff4c7
```
---
> Apim 3797 cron

- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-description-list/README.stories.mdx
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-description-list/gio-description-list.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-description-list/gio-description-list.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/gio-scss-components.scss
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.service.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-menu/gio-menu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.stories.ts
- ui-particles-angular/projects/ui-particles-angular/src/lib/oem-theme/oem-theme-menu-and-top-bar.stories.ts
**Issue**
Part of :https://gravitee.atlassian.net/browse/APIM-4442
---
```
npm install @gravitee/ui-schematics@12.5.0-add-gio-description-list-7756317
```
```
yarn add @gravitee/ui-schematics@12.5.0-add-gio-description-list-7756317
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.5.0-add-gio-description-list-7756317
```
```
yarn add @gravitee/ui-policy-studio-angular@12.5.0-add-gio-description-list-7756317
```
---
```
npm install @gravitee/ui-particles-angular@12.5.0-add-gio-description-list-7756317
```
```
yarn add @gravitee/ui-particles-angular@12.5.0-add-gio-description-list-7756317
```
---
> feat: add gio-description-list component

- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.component.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.html
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.component.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-formly-json-schema.service.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/code-editor.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/disableIf.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/displayIf.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/json-schema-example/enum.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.json
- projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchema.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/model/GioJsonSchemaContext.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/array-type.component.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/type-component/code-editor-type.component.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
- projects/ui-particles-angular/src/lib/public-api.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
- projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
- projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.html
- projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.ts
- projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.stories.ts
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-560
Part of : https://gravitee.atlassian.net/browse/APIM-5471
---
```
npm install @gravitee/ui-schematics@12.12.0-conditional-json-schema-0e9ba5d
```
```
yarn add @gravitee/ui-schematics@12.12.0-conditional-json-schema-0e9ba5d
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.12.0-conditional-json-schema-0e9ba5d
```
```
yarn add @gravitee/ui-policy-studio-angular@12.12.0-conditional-json-schema-0e9ba5d
```
---
```
npm install @gravitee/ui-particles-angular@12.12.0-conditional-json-schema-0e9ba5d
```
```
yarn add @gravitee/ui-particles-angular@12.12.0-conditional-json-schema-0e9ba5d
```
---
> Json Schema - impl displayOnlyIf to hide UI field

- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
- projects/ui-policy-studio-angular/src/lib/models/policy/SharedPolicyGroupPolicy.fixture.ts
- projects/ui-policy-studio-angular/src/lib/models/policy/SharedPolicyGroupPolicy.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-5391
---
```
npm install @gravitee/ui-schematics@12.20.0-prerequisitemessage-0633ed0
```
```
yarn add @gravitee/ui-schematics@12.20.0-prerequisitemessage-0633ed0
```
---
```
npm install @gravitee/ui-particles-angular@12.20.0-prerequisitemessage-0633ed0
```
```
yarn add @gravitee/ui-particles-angular@12.20.0-prerequisitemessage-0633ed0
```
---
> feat: PolicyStudio - add prerequisiteMessage for SPG

- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-5391
Hum trust me or i can show you 😁 
---
```
npm install @gravitee/ui-schematics@12.21.1-fix-ui-bug-1494b8e
```
```
yarn add @gravitee/ui-schematics@12.21.1-fix-ui-bug-1494b8e
```
---
```
npm install @gravitee/ui-particles-angular@12.21.1-fix-ui-bug-1494b8e
```
```
yarn add @gravitee/ui-particles-angular@12.21.1-fix-ui-bug-1494b8e
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.21.1-fix-ui-bug-1494b8e
```
```
yarn add @gravitee/ui-policy-studio-angular@12.21.1-fix-ui-bug-1494b8e
```
---
> Policy Studio - Fix UI bug

- projects/ui-particles-angular/src/lib/gio-banner/gio-banner.component.scss
- projects/ui-schematics/schematics/components/component-for-dialog/files/__name@dasherize__.component.ts.template
**Issue**
n/a
Small Improvement 
---
```
npm install @gravitee/ui-schematics@12.22.1-improvements-1a945dd
```
```
yarn add @gravitee/ui-schematics@12.22.1-improvements-1a945dd
```
---
```
npm install @gravitee/ui-particles-angular@12.22.1-improvements-1a945dd
```
```
yarn add @gravitee/ui-particles-angular@12.22.1-improvements-1a945dd
```
---
```
npm install @gravitee/ui-policy-studio-angular@12.22.1-improvements-1a945dd
```
```
yarn add @gravitee/ui-policy-studio-angular@12.22.1-improvements-1a945dd
```
---
> Improvements

- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.spec.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.component.ts
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- ui-particles-angular/projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-3046
https://github.com/user-attachments/assets/86f5d074-0f91-4c99-90cb-7d12ec7fa63f
---
```
npm install @gravitee/ui-particles-angular@7.60.1-apim-3046-add-message-level-conditions-3f72ce3
```
```
yarn add @gravitee/ui-particles-angular@7.60.1-apim-3046-add-message-level-conditions-3f72ce3
```
---
```
npm install @gravitee/ui-policy-studio-angular@7.60.1-apim-3046-add-message-level-conditions-3f72ce3
```
```
yarn add @gravitee/ui-policy-studio-angular@7.60.1-apim-3046-add-message-level-conditions-3f72ce3
```
---
> apim-3046-add-message-level-conditions

- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
- projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
**Issue**
https://gravitee.atlassian.net/browse/APIM-4332
- use prerequisiteMessage instead of description
- prefere matTooltip to lets more place to policy title
---
```
npm install @gravitee/ui-particles-angular@13.1.3-fix-c425ba2
```
```
yarn add @gravitee/ui-particles-angular@13.1.3-fix-c425ba2
```
---
```
npm install @gravitee/ui-schematics@13.1.3-fix-c425ba2
```
```
yarn add @gravitee/ui-schematics@13.1.3-fix-c425ba2
```
---
> fix: ps - simple UI improvement for SPG

- projects/ui-particles-angular/src/lib/oem-theme/gio-submenu/gio-submenu.component.ts
**Issue**
n/a
---
```
npm install @gravitee/ui-particles-angular@13.1.4-fix-dev-angular-error-ddb956a
```
```
yarn add @gravitee/ui-particles-angular@13.1.4-fix-dev-angular-error-ddb956a
```
---
```
npm install @gravitee/ui-schematics@13.1.5-fix-dev-angular-error-9f37c4f
```
```
yarn add @gravitee/ui-schematics@13.1.5-fix-dev-angular-error-9f37c4f
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.1.5-fix-dev-angular-error-9f37c4f
```
```
yarn add @gravitee/ui-policy-studio-angular@13.1.5-fix-dev-angular-error-9f37c4f
```
---
> fix: error ExpressionChangedAfterItHasBeenCheckedError on console

- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-message-form-dialog/gio-ps-flow-message-form-dialog.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-proxy-form-dialog/gio-ps-flow-proxy-form-dialog.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.scss
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.html
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.harness.ts
**Issue**
N/A, I just want to take a break to do something relaxing
Just test it on Storybook 
---
```
npm install @gravitee/ui-particles-angular@13.1.6-improve-ps-6b5d625
```
```
yarn add @gravitee/ui-particles-angular@13.1.6-improve-ps-6b5d625
```
---
```
npm install @gravitee/ui-schematics@13.1.6-improve-ps-6b5d625
```
```
yarn add @gravitee/ui-schematics@13.1.6-improve-ps-6b5d625
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.1.6-improve-ps-6b5d625
```
```
yarn add @gravitee/ui-policy-studio-angular@13.1.6-improve-ps-6b5d625
```
---
> Improve Policy Studio 

- angular.json
- projects/ui-particles-angular/gio-el/README.mdx
- projects/ui-particles-angular/gio-el/gio-el-editor-dialog/gio-el-editor-dialog.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor-dialog/gio-el-editor-dialog.component.scss
- projects/ui-particles-angular/gio-el/gio-el-editor-dialog/gio-el-editor-dialog.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-dialog/gio-el-editor-dialog.harness.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper-input.directive.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper-toggle.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper-toggle.component.scss
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper-toggle.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper-toggle.harness.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper.spec.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-helper/gio-el-editor-helper.stories.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.scss
- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.spec.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.stories.ts
- projects/ui-particles-angular/gio-el/models/ExpressionLanguageBuilder.spec.ts
- projects/ui-particles-angular/gio-el/models/ExpressionLanguageBuilder.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.scss
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
**Issue**
Part of https://gravitee.atlassian.net/browse/APIM-6925 and other FR by Product team
Just Init stub component for now. i will impl logic later
---
```
npm install @gravitee/ui-schematics@13.3.0-gio-el-editor-2-2eafee4
```
```
yarn add @gravitee/ui-schematics@13.3.0-gio-el-editor-2-2eafee4
```
---
```
npm install @gravitee/ui-particles-angular@13.3.1-gio-el-editor-2-b798683
```
```
yarn add @gravitee/ui-particles-angular@13.3.1-gio-el-editor-2-b798683
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.3.1-gio-el-editor-2-b798683
```
```
yarn add @gravitee/ui-policy-studio-angular@13.3.1-gio-el-editor-2-b798683
```
---
> gio-el-editor: Init stub component

- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
**Issue**
n/a
🙈 
---
```
npm install @gravitee/ui-particles-angular@13.5.2-fix-typo-df6dc5c
```
```
yarn add @gravitee/ui-particles-angular@13.5.2-fix-typo-df6dc5c
```
---
```
npm install @gravitee/ui-schematics@13.5.2-fix-typo-df6dc5c
```
```
yarn add @gravitee/ui-schematics@13.5.2-fix-typo-df6dc5c
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.5.2-fix-typo-df6dc5c
```
```
yarn add @gravitee/ui-policy-studio-angular@13.5.2-fix-typo-df6dc5c
```
---
> fix: corrects a spelling error

- projects/ui-particles-angular/gio-el/README.mdx
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor-condition-group/gio-el-editor-condition-group.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor-condition-group/gio-el-editor-condition-group.component.scss
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor-condition-group/gio-el-editor-condition-group.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor-condition-group/gio-el-editor-condition-group.harness.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor.component.scss
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor.component.spec.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-editor.stories.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-field/gio-el-field.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-field/gio-el-field.component.scss
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-field/gio-el-field.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-field/gio-el-field.harness.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-type/gio-el-editor-type-boolean/gio-el-editor-type-boolean.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-type/gio-el-editor-type-date/gio-el-editor-type-date.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-type/gio-el-editor-type-number/gio-el-editor-type-number.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-type/gio-el-editor-type-string/gio-el-editor-type-string.component.html
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-type/gio-el-editor-type-string/gio-el-editor-type-string.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor/gio-el-type/gio-el-editor-type.component.scss
- projects/ui-particles-angular/gio-el/models/Condition.ts
- projects/ui-particles-angular/gio-el/models/ConditionGroup.ts
- projects/ui-particles-angular/gio-el/models/ConditionModel.ts
- projects/ui-particles-angular/gio-el/models/ExpressionLanguageBuilder.spec.ts
- projects/ui-particles-angular/gio-el/models/ExpressionLanguageBuilder.ts
**Issue**
Part of https://gravitee.atlassian.net/browse/APIM-6925 and other FR by Product team
Continue to develop this component with various improvement. 
---
> EL: Progresse with improvement of UI, select field with Map & MultiMap option, autocomplete

- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-native-form-dialog/gio-ps-flow-native-form-dialog.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-native-form-dialog/gio-ps-flow-native-form-dialog.component.scss
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-native-form-dialog/gio-ps-flow-native-form-dialog.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-native-form-dialog/gio-ps-flow-native-form-dialog.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-native-form-dialog/gio-ps-flow-native-form-dialog.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-form-dialog/flow-native-form-dialog/gio-ps-flow-native-form-dialog.stories.ts
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.html
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.ts
- projects/ui-policy-studio-angular/src/lib/models/ConnectorsInfo.fixture.ts
- projects/ui-policy-studio-angular/src/lib/models/ConnectorsInfo.ts
- projects/ui-policy-studio-angular/src/lib/models/flow/Flow.fixture.ts
- projects/ui-policy-studio-angular/src/lib/models/policy/Policy.fixture.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.apim.stories.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.harness.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.model.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-7162
Add the support of Native API.
---
```
npm install @gravitee/ui-schematics@13.6.0-apim-7162-ps-native-api-0fe2323
```
```
yarn add @gravitee/ui-schematics@13.6.0-apim-7162-ps-native-api-0fe2323
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.6.0-apim-7162-ps-native-api-0fe2323
```
```
yarn add @gravitee/ui-policy-studio-angular@13.6.0-apim-7162-ps-native-api-0fe2323
```
---
```
npm install @gravitee/ui-particles-angular@13.6.0-apim-7162-ps-native-api-0fe2323
```
```
yarn add @gravitee/ui-particles-angular@13.6.0-apim-7162-ps-native-api-0fe2323
```
---
> feat: ps - support native api

- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.scss
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase-step/gio-ps-flow-details-phase-step.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.scss
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details-phase/gio-ps-flow-details-phase.harness.ts
- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.html
- projects/ui-policy-studio-angular/src/lib/components/flow-details/gio-ps-flow-details.component.scss
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.scss
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- projects/ui-policy-studio-angular/src/lib/components/policies-catalog-dialog/gio-ps-policies-catalog-dialog.component.html
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
**Issue**
n/a
Small improvement from UI/Ux team and me
https://github.com/user-attachments/assets/6cbbaa54-24a5-499b-9e22-204c31ecb7be
---
```
npm install @gravitee/ui-particles-angular@13.11.0-improvement-9cef003
```
```
yarn add @gravitee/ui-particles-angular@13.11.0-improvement-9cef003
```
---
```
npm install @gravitee/ui-schematics@13.11.0-improvement-9cef003
```
```
yarn add @gravitee/ui-schematics@13.11.0-improvement-9cef003
```
---
> Small PS improvement

- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.harness.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.harness.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-7958
---
```
npm install @gravitee/ui-particles-angular@13.12.0-13-x-fix-b065f4d
```
```
yarn add @gravitee/ui-particles-angular@13.12.0-13-x-fix-b065f4d
```
---
```
npm install @gravitee/ui-schematics@13.12.0-13-x-fix-b065f4d
```
```
yarn add @gravitee/ui-schematics@13.12.0-13-x-fix-b065f4d
```
---
```
npm install @gravitee/ui-policy-studio-angular@13.12.0-13-x-fix-b065f4d
```
```
yarn add @gravitee/ui-policy-studio-angular@13.12.0-13-x-fix-b065f4d
```
---
> fix: make duplicate only work

- projects/ui-policy-studio-angular/src/lib/components/flows-menu/gio-ps-flows-menu.component.ts
- projects/ui-policy-studio-angular/src/lib/models/flow/Flow.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-7958
---
```
npm install @gravitee/ui-schematics@14.1.1-apim-7958-abcdf25
```
```
yarn add @gravitee/ui-schematics@14.1.1-apim-7958-abcdf25
```
---
```
npm install @gravitee/ui-policy-studio-angular@14.1.1-apim-7958-abcdf25
```
```
yarn add @gravitee/ui-policy-studio-angular@14.1.1-apim-7958-abcdf25
```
---
```
npm install @gravitee/ui-particles-angular@14.1.1-apim-7958-abcdf25
```
```
yarn add @gravitee/ui-particles-angular@14.1.1-apim-7958-abcdf25
```
---
> fix: ps - remove id of duplicated flow

- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.ts
- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.stories.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.module.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
**Issue**
---
```
npm install @gravitee/ui-particles-angular@14.1.2-fix-sb-a1ebf36
```
```
yarn add @gravitee/ui-particles-angular@14.1.2-fix-sb-a1ebf36
```
---
```
npm install @gravitee/ui-policy-studio-angular@14.1.2-fix-sb-a1ebf36
```
```
yarn add @gravitee/ui-policy-studio-angular@14.1.2-fix-sb-a1ebf36
```
---
```
npm install @gravitee/ui-schematics@14.1.2-fix-sb-a1ebf36
```
```
yarn add @gravitee/ui-schematics@14.1.2-fix-sb-a1ebf36
```
---
> fix: storybook with GioMonacoEditor

- projects/ui-particles-angular/gio-el/gio-el-editor-input/gio-el-editor-input.component.spec.ts
- projects/ui-particles-angular/src/lib/gio-form-json-schema/gio-form-json-schema.stories.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.component.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.module.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/gio-monaco-editor.stories.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-language-el.service.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-language-json.service.ts
- projects/ui-particles-angular/src/lib/gio-monaco-editor/services/gio-monaco-editor.service.ts
- projects/ui-particles-angular/src/lib/public-api.scss
**Issue**
n/a
🤞 
---
```
npm install @gravitee/ui-policy-studio-angular@14.1.4-fix-monaco-19177dd
```
```
yarn add @gravitee/ui-policy-studio-angular@14.1.4-fix-monaco-19177dd
```
---
```
npm install @gravitee/ui-particles-angular@14.1.4-fix-monaco-c912c9c
```
```
yarn add @gravitee/ui-particles-angular@14.1.4-fix-monaco-c912c9c
```
---
```
npm install @gravitee/ui-schematics@14.1.4-fix-monaco-c912c9c
```
```
yarn add @gravitee/ui-schematics@14.1.4-fix-monaco-c912c9c
```
---
> fix: monaco editor with cypress

- projects/ui-particles-angular/src/lib/public-api.scss
**Issue**
---
```
npm install @gravitee/ui-particles-angular@14.1.2-improve-btn-toggle-d7fedd2
```
```
yarn add @gravitee/ui-particles-angular@14.1.2-improve-btn-toggle-d7fedd2
```
---
```
npm install @gravitee/ui-policy-studio-angular@14.1.2-improve-btn-toggle-d7fedd2
```
```
yarn add @gravitee/ui-policy-studio-angular@14.1.2-improve-btn-toggle-d7fedd2
```
---
> fix: forward gio-button-toggle-group-icons to use in scss files

- package.json
- projects/ui-policy-studio-angular/package.json
- projects/ui-policy-studio-angular/src/lib/components/step-edit-dialog/gio-ps-step-edit-dialog.stories.ts
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.html
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.scss
- projects/ui-policy-studio-angular/src/lib/components/step-form/gio-ps-step-form.component.ts
- projects/ui-policy-studio-angular/src/lib/models/PolicySchemaFetcher.ts
- projects/ui-policy-studio-angular/src/lib/models/policy/PolicySchema.fixture.ts
- projects/ui-policy-studio-angular/src/lib/policy-group-studio/gio-policy-group-studio.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.component.spec.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.model.ts
- projects/ui-policy-studio-angular/src/lib/policy-studio/gio-policy-studio.service.ts
- yarn.lock
In this PR we add a check on plugin documentation types in the policy studio
---
```
npm install @gravitee/ui-schematics@15.0.0-handle-md-doc-09ea861
```
```
yarn add @gravitee/ui-schematics@15.0.0-handle-md-doc-09ea861
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.0.0-handle-md-doc-7b260d9
```
```
yarn add @gravitee/ui-policy-studio-angular@15.0.0-handle-md-doc-7b260d9
```
---
```
npm install @gravitee/ui-particles-angular@15.0.0-handle-md-doc-7b260d9
```
```
yarn add @gravitee/ui-particles-angular@15.0.0-handle-md-doc-7b260d9
```
---
> feat: handle multiple policy documentation types

- projects/ui-particles-angular/src/lib/gio-el/gio-el.service.ts
**Issue**
https://gravitee.atlassian.net/browse/APIM-9968
Quick fix
---
```
npm install @gravitee/ui-schematics@15.7.0-mba-apim-9968-3a95980
```
```
yarn add @gravitee/ui-schematics@15.7.0-mba-apim-9968-3a95980
```
---
```
npm install @gravitee/ui-policy-studio-angular@15.7.0-mba-apim-9968-3a95980
```
```
yarn add @gravitee/ui-policy-studio-angular@15.7.0-mba-apim-9968-3a95980
```
---
```
npm install @gravitee/ui-particles-angular@15.7.0-mba-apim-9968-3a95980
```
```
yarn add @gravitee/ui-particles-angular@15.7.0-mba-apim-9968-3a95980
```
---
> fix: missing setter in GioElService
